### ISSUE TITLE
Help：Unable to send frames greater than 1500

### ISSUE THREAD

**Issue by wshe1** [bastibl/gr-ieee802-11#106]
Hallo, Bastian.
I modified the program to expect to use the Socket PUD to send a frame length of 5000. However, a maximum of 1500 frames can be sent. I changed the max payload from 1500 to 5500, but it can only send 1500.The following is my modified program, what should I do?
![screenshot from 2018-04-09 23-36-49](https://user-images.githubusercontent.com/33091503/38540391-6cab1d26-3cce-11e8-9022-149ba1303cee.png)

**Comment by bastibl** [comment]
Looks good.
What do you mean with it doesn't work? Is there a warning or an error? Are the block buffers too small? Where in the TX chain does it break? Are you shure it breaks in TX (an not in RX)?

**Comment by wshe1** [comment]
Hallo, Bastian.
The problem just solved, under the solution method。But I encountered your new problem and I need your answer.
![screenshot from 2018-04-10 01-53-36](https://user-images.githubusercontent.com/33091503/38547096-e98ddaec-3ce0-11e8-8f3d-1220f4cce476.png)
![screenshot from 2018-04-10 01-39-26](https://user-images.githubusercontent.com/33091503/38547106-f0f71f82-3ce0-11e8-83e1-cc770ce25e9f.png)
![screenshot from 2018-04-10 01-52-31](https://user-images.githubusercontent.com/33091503/38547107-f20488c4-3ce0-11e8-8211-2a2379c9a728.png)

**Comment by Nattaro13** [comment]
Hallo Bastian,

We have a similar problem as @wshe1 even after we have pulled the fixes and made the min output buffer sizes much larger in the corresponding python scripts as well. 

```
sched: <block chunks_to_symbols (9)> is requesting more input data
  than we can provide.
  ninput_items_required = 80496
  max_possible_items_available = 65535
  If this is a filter, consider reducing the number of taps.
```

Could we get your help on this as well?

Thank you!

**Comment by bastibl** [comment]
You have to increase the buffer size. As I said:

> The buffer sizes can be changed in GRC (Advanced -> Min Output Buffer Size)
