### ISSUE TITLE
A question about  OFDM PHY

### ISSUE THREAD

**Issue by bigtree123321** [bastibl/gr-ieee802-11#110]
Hi,
I want to change the source code of OFDM PHY, how can I do it?

**Comment by bastibl** [comment]
The PHY is a hierarchical block that is put together in GNU Radio Companion. You can change it by opening `examples/wifi_phy_hier.grc` in GNU Radio Companion.

If you want to change the functionality of one block, you'll have to adapt its source (it's in the `lib` folder), recompile, and install.
