### ISSUE TITLE
USRP like Tx

### ISSUE THREAD

**Issue by emozo** [bastibl/gr-ieee802-11#112]
Hello Bastian,

I have read your called article ¨Performance Assessment of IEEE 802.11p with an Open Source SDR-based Prototype¨ and have some question. The comunication between the MK5 and USRP is very well, I can see the decoded simbols on the contestation, the wife_rx file is executing well. My problem arrive when I reverse the comunication order, USRP and MK5, the wifi_tx is not executing very well. I have seen other problem similar in this page, for that reason I adding samples front of the frame and offset of 6 MHZ, but I don´t see the frame in the MK5. When I am running the wifi_tx the A Led are blinking. Could you advice me something ? Is the AGC block included in the gr-ieee802-11 ? There are any performance different between the master and next branch of the gr-ieee802-11 ? 

Thank you for helping, regards...

**Comment by bastibl** [comment]
No, by default, there is no AGC (and, in any case, it would only impact RX w/ the USRP, which seems to work for you).
I'd first check if it's the MK5 or the SDR. Try receiving the frames either with another SDR or with a normal WiFi card (with 20MHz and on the 5GHz band). Maybe it's just the MK5. At least I found that it's not always trivial to configure. You should not have to add anymore samples. The default TX flow graph already does that. Make sure to start with the unmodfied flow graphs.

**Comment by emozo** [comment]
Hello,

I have followed your advice and I have received the frames with other SDR
very well. Then the problem seems that about the MK5 configuration like you
thought  ago.  In the MK5, I only use the chconfig and test-rx commads.
With these two commads I can to tramitter and receiver frame if I use two
MK5 very well.  Could you advice me in this configuration ?

Regards, ..

2018-04-24 22:24 GMT+02:00 Bastian Bloessl <notifications@github.com>:

**Comment by bastibl** [comment]
IIRC, it also took us quite some time until we understood how to configure the MK5. But that's quite some time ago and I have no longer a device at hand. You should contact Cohda Wireless (or check their Wiki) if you have problems configuring the device.

**Comment by emozo** [comment]
Ok Thank you for your advices, Thanks..

2018-04-27 13:05 GMT+02:00 Bastian Bloessl <notifications@github.com>:
