### ISSUE TITLE
Configurable sync/training fields

### ISSUE THREAD

**Issue by davidzwa** [bastibl/gr-ieee802-11#117]
Same question here as [issue](https://github.com/bastibl/gr-ieee802-11/issues/116), less tl;dr.

In order to change the STF and LTF from 802.11p to something for 802.11ah with f.e. repeated training fields, could the receiver end be made more flexible? I think right now lot of the blocks are assuming/hardcoding timing and symbol lengths.

Can you give me some pin-point direction to what functions I should take care of understanding first?

**Comment by davidzwa** [comment]
Same here, if you can help me out, I might be able to help you out with a PR ;)

**Comment by bastibl** [comment]
I guess this was answered in the other issue.
