### ISSUE TITLE
About WiFi preamble

### ISSUE THREAD

**Issue by uioi** [bastibl/gr-ieee802-11#125]
I successfully implemented the transmitter and receiver between a X300 and a B210. I'm at the stage to customize my own program. But I'm not sure with one thing. I know at the receiver side, the receiver correlates the incoming signal to detect the preamble and also for phase/frequency synchronization. However, I didn't find where the preamble is inserted on the sender side. I did find kind of preamble insertion block after the OFDM cyclic prefixer in old material/paper but I can't find it in the current implementation of wifi_phy_hier or wifi_tx.

**Comment by bastibl** [comment]
See the Carrier Allocator in WiFi_phy_hier. The sync words are the preamble symbols.
