### ISSUE TITLE
EnvironmentError: OSError: error in pthread_setschedparam

### ISSUE THREAD

**Issue by saogo** [bastibl/gr-ieee802-11#127]
Hi good afternoon bastian... I've been working on your project and now I see this error ..... in the Wi-Fi reception and I do not know how to fix this error ...EnvironmentError: OSError: error in pthread_setschedparam... thanks for you time

**Comment by bastibl** [comment]
Hi, that sounds like a problem of GNU Radio, not this module. Looks like GNU Radio fails to configure the thread.
Please try a flow graph from the GNU Radio examples and see if it also raises the error.

If you think the error is related to this module, please provide more details. (what are you trying to run, how did you install the module (and which branch), how did you install GNU Radio (and which version), what system are you running, etc.)
