### ISSUE TITLE
pybinding install

### ISSUE THREAD

**Issue by fate118** [bastibl/gr-ieee802-11#136]

**Comment by bastibl** [comment]
I never tried to build the module on Windows. Still, I don't think that your error is related to this module. It looks like you are trying to build some other software.

**Comment by fate118** [comment]
thanks
I did the following things
1-Install Visual Studio 2017 Community.
2-Install CMake.
3-The following command will instruct pip to download the latest source code from GitHub, compile everything and install the package:
pip3 install git+https://github.com/dean0x7d/pybinding.git

Is it wrong cmake?
i just install it,

**Comment by bastibl** [comment]
4- open issue at random software project on GitHub :-)

This is a GNU Radio module for WLAN. I guess you should  post your issue here:
https://github.com/dean0x7d/pybinding/issues

**Comment by fate118** [comment]
5-thanks
