### ISSUE TITLE
File Sink fail

### ISSUE THREAD

**Issue by marvinlwc97** [bastibl/gr-ieee802-11#143]
Dear Bastian Bloessl,
By using the default configuration, it seems that I am not getting anything through the wireshark connector:
![20181129_105942](https://user-images.githubusercontent.com/45310991/49217742-4fa3a900-f3c6-11e8-8d3a-e591bc3e08f1.jpg)
May I know what I should change for it to output the pcap files?

Thank you very much

**Comment by bastibl** [comment]
The gray shading of the blocks indicates that they are disabled. Click on them an press 'E' to activate them, or use the corresponding menu entry.

I'd recommend to checkout the GNU Radio Wiki and documentation on more information about using GNU Radio.
