### ISSUE TITLE
Installation in MAC OS

### ISSUE THREAD

**Issue by sayaz** [bastibl/gr-ieee802-11#151]
Hi Bastian,
I am already using your blocks in Ubuntu OS where everything is working fine. I am not very fluent in using macOS, but it is a need for me to run your blocks in macOS. 

macOS High Sierra version 10.13.6
- Installed Gnuradio (running fine)
```
sudo port install swig
sudo port install log4cpp
git clone git://github.com/bastibl/gr-ieee802-11.git
cd gr-ieee802-11
mkdir build
cd build
cmake ..
make
sudo make install
sudo ldconfig
```

The module is installed, but i am not seeing it in the GUI after refreshing. I am assuming, I have got some path mismatch though there are no errors. Can you help me to solve this ?

**Comment by sayaz** [comment]
Sorry for the trouble. You can close this issue. I saw the solution in your comments on another post as below, this has solved the problem.

[grc]
global_blocks_path = /opt/local/share/gnuradio/grc/blocks
local_blocks_path = ~/usr/share/gnuradio/grc/blocks

**Comment by bastibl** [comment]
Great that it worked.
