### ISSUE TITLE
Unable to build gr-foo

### ISSUE THREAD

**Issue by arun121cs** [bastibl/gr-ieee802-11#152]
Hello there,
I am trying to build gr-foo but when i try to make, it comes an error as
![screenshot from 2019-02-04 13-57-14](https://user-images.githubusercontent.com/35321939/52197349-42eb7780-2885-11e9-8488-93904b5d2031.png)

What is the possible reason and what i need to install before building this.
Thanks in advance.

**Comment by bastibl** [comment]
This was already addressed here:
https://github.com/bastibl/gr-ieee802-11/issues/128
https://github.com/bastibl/gr-foo/issues/8
https://github.com/bastibl/gr-foo/issues/7
https://github.com/bastibl/gr-foo/issues/6

You use the wrong branch. Probably GNU Radio maint with the next branch of this module. Please try the  master branch of the module

**Comment by arun121cs** [comment]
I did try the master branch. Again the same problem is there. Do i need to build everything from scrach?

**Comment by bastibl** [comment]
You need to rebuild the module. If this doesn't work, please give a bit more details. How did you install GNU Radio, which version, what branch of the module did you install.

**Comment by arun121cs** [comment]
I installed GNU radio using pybombs which is given in readme instead of building from source. I am also confused that which branch it takes when it installs from pybomb.

**Comment by bastibl** [comment]
There are three GNU Radio versions in pybombs. The default GNU Radio recipe pointed for a while to the wrong branch. Please make sure to 
`pip install --upgrade PyBOMBS`
`pybombs recipes update`
`pybombs install gnuradio`
`pybombs install gr-ieee80211`
With this you should end up with compatible version

**Comment by arun121cs** [comment]
Can i know how to completely uninstall and then which pair of branches for both GNU radio and gr-foo i need to clone?

**Comment by arun121cs** [comment]
Since i am trying to install gr-foo, should not the last command has to be pybombs install gr-foo?

**Comment by arun121cs** [comment]
I got it now. I was not able to use the same branch as i did not uninstall that. Thanks.

**Comment by girs1982** [comment]
pybombs install gr-ieee80211 not worck no recepties!!!!

**Comment by bastibl** [comment]
Holy shit, not worck no recepties!?!?!?1

Please read the thread, do as suggested, and if you still have a problem, then please provide a more comprehensive report of your issue.

**Comment by girs1982** [comment]
not work!!!shit cant was holly,write error need recept
try it self

**Comment by girs1982** [comment]
ok i install it))) ,but not all work on usrp, i send errors later,for install need checkout it to maint-3.7 all repos
