### ISSUE TITLE
PHY Pad bits for data field

### ISSUE THREAD

**Issue by dbj4225** [bastibl/gr-ieee802-11#158]
Hi,

Seems no pad bits are added in generate_bits() function.
![image](https://user-images.githubusercontent.com/47696555/53472895-f6174d00-3a8e-11e9-9357-09205093b22c.png)
![image](https://user-images.githubusercontent.com/47696555/53472918-0a5b4a00-3a8f-11e9-8729-6098d052cbcc.png)
only service field is appended.

Can you please clarify if I am mistaken and some where else this phy padding is taken care?

**Comment by bastibl** [comment]
Padding is already included in n_data_bits. See utils.cc/frame_param. This function mainly puts the payload at the right place.

**Comment by dbj4225** [comment]
frame_param calculates the no of data bits including padding. But I could not see where appending of these padded bits actually  happens in utils.cc/frame_param.Is this done somewhere else?
![image](https://user-images.githubusercontent.com/47696555/53478596-3382d700-3a9d-11e9-8a27-b7a4515f188a.png)

Can you please help with this regard..

**Comment by bastibl** [comment]
I don't understand the problem. How would you expect that this should look like? Like adding byte to the buffer? From this lines of code, you can see that `n_data_bits` includes padding. The code in the mapper allocates a buffer of size `n_data_bits` and copies the payload in the middle, i.e., not at the end. So there are some bits left at the end of the buffer, which is the padding.
Please take a bit more time to familiarize yourself with the code (and maybe C++). Your asking question with high frequency, all of them general WLAN or programming stuff. This is mainly an issue tracker for issues of the code.
