### ISSUE TITLE
Wireshark do not capture generated frames

### ISSUE THREAD

**Issue by khg2478** [bastibl/gr-ieee802-11#160]
Hi. I think I might be too new to this area. Sorry for bothering you.

I have checked some of related web pages below to learn about this project. 

https://www.wime-project.net/
http://www.ccs-labs.org/software/gr-ieee802-11/
https://github.com/bastibl/gr-ieee802-11

We are currently thinking of doing some related project based on ieee802.11b. Before that, I want to learn how to use gnuradio, uhd usrp, and wireshark properly.

Is there any website you can recommend me for fundamental understanding of gnuradio and all?

I ran both of wifi_tx.grc and wifi_rx.grc on two different PCs and was able to see some signals detected on wifi_rx.grc side as shown below.

![screenshot from 2019-03-04 18-56-45](https://user-images.githubusercontent.com/2188129/53725428-55ba9180-3eaf-11e9-912a-0e4082bc6d18.png)

However, wireshark does not show me any captured frames. I assume that because of the error during the execution.

/usr/share/uhd/images/usrp_b200_fw.hex...
void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "" under id 195
void DBusMenuExporterPrivate::addAction(QAction*, int): Already tracking action "" under id 196

Based on my understanding by setting frequency channel, I can capture specific packets in a channel. I can see my wifi_rx.grc running program captures this packets as shown in in-phase diagram. However, 
wireshark does not seem to capture packets properly.

radiotap.channel.freq == 2412

![freq](https://user-images.githubusercontent.com/2188129/53730684-03cc3880-3ebc-11e9-9ab5-e0385237eedc.png)

Could you recommend me some materials to study those projects?

Also, I wonder whether there is any available 802.11b transceiver and receiver.

I apologize for my basic questions.. Thanks.

**Comment by bastibl** [comment]
I'd suggest you have a look at the [GNU Radio Wiki](https://wiki.gnuradio.org/index.php/What_is_GNU_Radio%3F). The tutorial might be helpful even if it is not directly related to your project.

Some years ago, there was a IEEE 802.11b receiver (I think it was called BBN), but it is not actively maintained. And, AFAIK, it was not a CPU implementation but tight to the FPGA of an older USRP generation.

The signal on 178 looks good. The Wireshark blocks are disabled (grayed out) by default. When you enable them in GRC, the data will be written to a file. Open the file in Wireshark.

On 2.4GHz, there are no 10MHz signals. You will have to set the sample rate to 20MHz and make sure that there are 11g transmissions. (Easiest might be to open an Ad Hoc network with a MacBook). If you use any other device, make sure it is 11g without backwards compatibility mode.

**Comment by khg2478** [comment]
@bastibl 
Super. It perfectly works. Thank you so so much!
