### ISSUE TITLE
Signal Bandwidth

### ISSUE THREAD

**Issue by hsberger** [bastibl/gr-ieee802-11#168]
I am trying to use the wifi_tx flowgraph to generate a WiFi transmission in a wireless coexistence test.  I have a couple of things I don't understand about what I am seeing.

First, when I change the bandwidth in wifi_phy_hier I don't see the generated signal coming from the USRP change.  Changing the sample rate does change the signal bandwidth.

Second, the signal skirts are very wide, almost 100 MHz.  The signal goes down by 20 dB as expected but then flattens out, especially on the low frequency side.  For my purpose I would like to have the signal well contained in its bandwidth.

Thanks in advance for your help.

**Comment by bastibl** [comment]
Please start from the transceiver flow graph, provided in the examples. It already supports changing the bandwidth. (While the PHY also has a sample rate parameter, the BW change comes from changing the sample rate of the SDR).

The fact that the signal spreads out suggests that you either removed the multiply const block from the example or set the gain way too high.
