### ISSUE TITLE
Block key not found

### ISSUE THREAD

**Issue by yunhubuyi** [bastibl/gr-ieee802-11#169]
Hi Bastian,

when loading wifi_phy_hier.grc, it shows that
Block key "ieee802_11_chunks_to_symbols_xx" not found
Block key "ieee802_11_decode_mac" not found
Block key "ieee802_11_frame_equalizer" not found
Block key "ieee802_11_mapper" not found
Block key "ieee802_11_moving_average_xx" not found
Block key "ieee802_11_moving_average_xx" not found
Block key "ieee802_11_sync_long" not found
Block key "ieee802_11_sync_short" not found

my Block paths is "/home/xx/.grc_gnuradio" and "/home/xx/prefix/share/gnuradio/grc/blocks"
Could you help me, many thanks.

**Comment by bastibl** [comment]
Your block path is not `<something/.grc_gnuradio`. You have to set the local blocks path in this file to the location where the xml files ended up during installation. Please see here:
https://www.wime-project.net/installation/

After that, restart GRC or reload the blocks through the menu.
