### ISSUE TITLE
Can't build maint-v.37 branch on ARMv8

### ISSUE THREAD

**Issue by akshayy29** [bastibl/gr-ieee802-11#175]
I'm having the same exact issue posted here: https://github.com/bastibl/gr-ieee802-11/issues/120#issue-334109703 .

```
I'm trying to build this on a Raspberry Pi, but make fails with the following:
[ 7%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/moving_average_cc_impl.cc.o c++: error: unrecognized command line option '-msse2'

Presumably, the issue is that ARM doesn't have -msse2. I commented out the msse2 line from CMakeLists.txt and I get a different (also x86-specific) error:
In file included from /root/sdr/gr-ieee802-11/lib/decode_mac.cc:20:0: /root/sdr/gr-ieee802-11/lib/viterbi_decoder.h:20:10: fatal error: xmmintrin.h: No such file or directory #include <xmmintrin.h> 
```

I also tried contacting rcetin, since he solved the issue using cross compilation & modifying the sources, but haven't got any reply from him yet.

**Comment by bastibl** [comment]
Not sure what exactly you commented out, but can you please try commenting out this line:

**Comment by akshayy29** [comment]
You're referring us to maint-3.8, but we are using maint-3.7,

**Comment by bastibl** [comment]
maint-3.7 doesn't have this compile switch. Either "back port" the generic implementation to 3.7 (copy-pasting a file and some cmake), switch to 3.8, or use an older version of the 3.7 branch that worked with GNU Radio next.

**Comment by dattajigosavi** [comment]
We followed the steps provided in Jetson Nano device.The generic implementation was copied in the CMakeLists.txt in the "lib" folder .
![Screenshot from 2019-07-11 17-12-38](https://user-images.githubusercontent.com/42787984/61744047-012f8a00-ad5c-11e9-8499-e0b8c14d4c9a.png)
![Screenshot from 2019-07-11 17-13-16](https://user-images.githubusercontent.com/42787984/61744063-055ba780-ad5c-11e9-8a6e-123d40565713.png)


After executing the make command on the terminal says the 100% completion. But when we tried to use the examples we got a error states  "block  not found" and ieee 802_11 not defined.
![Screenshot from 2019-07-11 18-01-26](https://user-images.githubusercontent.com/42787984/61743193-61bdc780-ad5a-11e9-8876-caca621fa516.png)
![Screenshot from 2019-07-11 18-01-53](https://user-images.githubusercontent.com/42787984/61743199-63878b00-ad5a-11e9-93d0-a963500260f1.png)

What is your advice to solve this error?

**Comment by bastibl** [comment]
The hierarchical block has to be build. After that blocks have to be reloaded or GRC has to be restarted. Please see the installation instructions:
https://www.wime-project.net/installation/

**Comment by tranzmatt** [comment]
It makes no sense to hardcode Intel's "sse2" flag with GNURadio being built on ARM devices.

**Comment by gmartina** [comment]
How can you build the hierachical block in an embedded platform with just gnuradio, without gnuradio companion? 

thankyou

**Comment by bastibl** [comment]
you can build it with `grcc` which is installed as part of GNU Radio.

**Comment by gmartina** [comment]
i dont have gnuradio companion installed in my embedded device. Do you mean i can build it in a desktop PC and use it in my embedded device?

**Comment by gmartina** [comment]
(i meant i dont have grcc installed, i have only gnuradio instaled, minimal image, no graphics)

**Comment by bastibl** [comment]
`grcc` does not use graphics. Anyway, if it is not available, you'd have to build the block on the host and copy it over. The  generated Python script and Block definition are usually under `~/.grc_gnuradio`).

**Comment by gmartina** [comment]
@bastibl  Thank you for you fast reply!
