### ISSUE TITLE
cant done Dot11Deauth() attack

### ISSUE THREAD

**Issue by girs1982** [bastibl/gr-ieee802-11#178]
i start script ,launch flow 
![image](https://user-images.githubusercontent.com/13913400/61536631-e8387900-a9e9-11e9-9831-e4dadaff9456.png)
but nothing connection stable,what i was wrong???

**Comment by bastibl** [comment]
You use a gain of 0. Try something like 0.75.  Also something is wrong with the tags. Try setting the TSB Len Key to "packet_len". Looks like it's "packet len".

**Comment by girs1982** [comment]
![image](https://user-images.githubusercontent.com/13913400/61537608-69910b00-a9ec-11e9-94c9-a7fc35371519.png)
nothing

**Comment by bastibl** [comment]
->->->->->->-> packet_len <-<-<-<-<-<-<-<-

**Comment by girs1982** [comment]
what need to write?

**Comment by bastibl** [comment]
I wrote it twice. That should be enough.

**Comment by girs1982** [comment]
not worck
