### ISSUE TITLE
I cant see any packets wlan0 monitor mode!!!

### ISSUE THREAD

**Issue by Gonzaless-Chura** [bastibl/gr-ieee802-11#182]
i run tx example,but nothing not see in monitor wlan!!!
![image](https://user-images.githubusercontent.com/53256406/61780130-ca3a9200-adb6-11e9-918c-4dc2c3195ba0.png)
i try like it https://www.youtube.com/watch?v=bKe7oTLmru4
but cant done,where error???

**Comment by bastibl** [comment]
Please see the `rx_demo.sh` script in the apps folder. Also you started Wireshark to listen on you normal WLAN card. You can either log to file and open the file in wireshark (as shown in the example flow graph), create a FIFO and read from the FIFO as shown in the `rx_demo.sh` script or create a TUN/TAP interface and listen on this interface (also shown in the `rx_demo.sh` script.

**Comment by Gonzaless-Chura** [comment]
what need to do ,for see packets standard wlan monitor???, i create usrp_wifi_txr,like esp8266 jammer,but not fully understand yours job!!!

**Comment by bastibl** [comment]
Again, please checkout and use the `rx_demo.sh` script. If you have any specific questions, feel free to ask. But please stop this "hlp plx, thing not working!!!"-questions.

**Comment by Gonzaless-Chura** [comment]
i need send death packet in my wifi AP,how i can it done,use yours job???
nothing not packets
![image](https://user-images.githubusercontent.com/53256406/61874988-543b4580-aef2-11e9-974f-cf43b61aadc2.png)

**Comment by bastibl** [comment]
...............
