### ISSUE TITLE
Transmitting Data from a File

### ISSUE THREAD

**Issue by is353** [bastibl/gr-ieee802-11#188]
Hello,
I am trying to transmit and share timestamps between two nodes. Is possible to transmit specific data from a file using GNURADIO. If so, could please explain the procedure?

Thank you

**Comment by bastibl** [comment]
I'm not sure what exactly you are trying to do, but you can send data by feeding a string or a GNU Radio PDU to the MAC block. The example demonstrates how to send a string. The easiest way to send your custom data (without writing a block on your own) would be to connect a Socket PDU block to the MAC block and send UDP packets, containing the timestamp from the file (or whatever you want to send), to the UDP Source.

A simple example that shows how to send data with Python to the Socket PDU block is here:
https://github.com/bastibl/gr-ieee802-15-4/blob/maint-3.8/utils/udp.py
