### ISSUE TITLE
Scapy + WLAN + USRPs

### ISSUE THREAD

**Issue by tingjunchen** [bastibl/gr-ieee802-11#189]
Hi Bastian,

I am trying to use the scapy + wlan script (https://gist.github.com/bastibl/abedd2f8c656048152d3c30c249dc02e) and send 802.11 beacons over the air using USRPs. The eventual goal is to let a commercial wifi card in monitor mode pick up the 802.11 wifi beacons from a USRP. 

When debugging this, I set up a pair of USRPs running the 802.11 Tx and Rx and use the scapy script to send 802.11 beacon frame (I use the exact same flowgraph you had on https://www.bastibl.net/gnuradio-wlan-scapy/ but with the USRP sink connect to a USRP N201 device). However, I was not able to get the beacons decoded correctly on the Rx side.

After turning on the debug mode of the "WiFi Decode MAC" block, I got the following output

psdu size45
80 00 00 00 ff ff ff ff ff ff 23 23 23 23
23 23 23 23 23 23 23 23 00 00 00 00 00 00 00 00
00 00 64 00 00 00 00 07 47 52 20 57 4c 41 4e
..........############..........d.....GR WLAN
checksum wrong - dropping

Any thoughts what is going on? It seems like the beacon frame was not generated properly but maybe I am missing something.

Thank you for your time and help!

**Comment by bastibl** [comment]
please try the commands in these slides:

https://archive.fosdem.org/2019/schedule/event/gr_scapy/attachments/slides/3366/export/events/attachments/gr_scapy/slides/3366/gnuradio_meets_scapy.pdf

It might be related to the checksum. To make sure that Scapy is working, use the loopback flowgraph and see if the messages can be decoded. You can also use Wireshark to inspect the pcap file and make sure that all fields are set correctly.
