### ISSUE TITLE
Loopback stuck for pdu_length greater than 80 

### ISSUE THREAD

**Issue by asarma13** [bastibl/gr-ieee802-11#190]
Hi Bastian,

I am trying to run the loopback.grc with the following modification. WiFi PHY Hier frequency = 2.412G, bandwidth = 20M. I am able to send the packets properly (verified by looking into the pcap file) till pdu_length = 80. Below is the error that I get when I use a pdu_length of 100 bytes. From the logs, it looks like the problem is with the buffer size  GR_FIXED_BUFFER_SIZE. Kindly let me know where I need to change to resolve this issue.

************************************
* MESSAGE DEBUG PRINT PDU VERBOSE *
((crc_included . #t))
MAPPER called offset: 0   length: 0pdu_length = 128

MAPPER: received new message
contents = 
0000: 08 00 00 00 42 42 42 42 42 42 23 23 23 23 23 23 
0010: ff ff ff ff ff ff 00 00 7f 7f 7f 7f 7f 7f 7f 7f 
0020: 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 
0030: 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f MAPPER called offset: 0   length: 7f 7f 7f 7f 2112
7f 
0040: 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 
0050: 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 
0060: 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 
0070: 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 7f 9d 18 4d 4c 
***********************************

**thread[thread-per-block[16]: <block foo_packet_pad2(32)>]: Buffer too small for min_noutput_items**

MAPPER called offset: 0   length: 2112

Thanks,
Ayushman

**Comment by bastibl** [comment]
That's a problem of GNU Radio, which ignores the buffer settings. I issued a PR a month ago..
https://github.com/gnuradio/gnuradio/pull/2733
