### ISSUE TITLE
Name 'ieee802_11' is not defined

### ISSUE THREAD

**Issue by yunhubuyi** [bastibl/gr-ieee802-11#193]
Hi Bastian,

When i run wifi_phy_hier.grc in my MAC, i meet this problem.
What may be wrong? How can i fix it?

Thank you for your time and help!
![image](https://user-images.githubusercontent.com/31362986/65368915-582cdf00-dc79-11e9-9fe3-aa72ca7f0c44.png)

**Comment by yunhubuyi** [comment]
Oh, i fixed it by setting the LD_LIBRARY_PATH and LIBRARY_PATH.

**Comment by bastibl** [comment]
Great that it worked.
