### ISSUE TITLE
Unable to setup unidirectional communication - wifi_tx, wifi_rx

### ISSUE THREAD

**Issue by addyvenkat** [bastibl/gr-ieee802-11#197]
Hi @bastibl 
First of all, thank you so much for your contribution.

The SDR that I'm using: USRP B200mini
GNUradio and gr-ieee802-11: maint-3.7 versions
OS: Ubuntu16.04
5GHz band

Wifi_tx:
I'm not able to receive any frames from the SDR while looking at my wifi card in monitor mode using tcpdump. 

wifi_rx:
I'm not able to run the packetspammer.c application to manually inject the frames.

I would highly appreciate your help. 
My experience with SDRs is very new. Apologizing if I missed anything trivial.

**Comment by bastibl** [comment]
What you are basically saying is, you tried but it didn't work.
Are there any errors or underruns? Is the antenna connected to the correct port? Do you use 20MHz sample rate? Is the WLAN card listening on the correct channel? Did you try to adapt the gain? etc etc etc
There is some more information here: https://www.wime-project.net/installation/
If you still have problems, please be a bit more verbose.
