### ISSUE TITLE
channel error in  wireshark and power of signal

### ISSUE THREAD

**Issue by adjmxx** [bastibl/gr-ieee802-11#198]
Hi, good night my name is Anderson Diaz, i'm studying in university of Carabobo Venezuela, i'm doing an networks analyzer WLAN with you receiver ieee802.11a/g/p is my theme of thesis, i want adjunct an spetrograme and sweep in frequency automatic; but i have a problem  with frames in wireshark, when see the frames in wireshark "802.11 Radio information"  the channel is 178MHz but will should be  2417MHz that is channel in the wich my router is transmittering.

Exists the possibility that can you help me. Thaks!!

**Comment by adjmxx** [comment]
I'm using the  hackrf one

**Comment by adjmxx** [comment]
![2019-11-21-202306_1366x768_scrot](https://user-images.githubusercontent.com/20531970/69387665-e8e56280-0c9c-11ea-949c-51ce3696fbbf.png)

**Comment by bastibl** [comment]
This value is hard-coded at the moment. If it is crucial for you, you'd have to add the current frequency/channel as meta data to the frame. At the moment, only the SNR and the MCS is annotated. See the code for these two values to see how you can add more metadata.

**Comment by adjmxx** [comment]
thanks!!

**Comment by bastibl** [comment]
you're welcome
