### ISSUE TITLE
USRP B210 gnuradio error

### ISSUE THREAD

**Issue by Pradyumna007** [bastibl/gr-ieee802-11#203]
Hi, I followed all the steps. But I am getting this error 
The FPGA build is not compatible with the host code build.
Please run:

 "/usr/lib/x86_64-linux-gnu/uhd/utils/uhd_images_downloader.py"

I have set environment variables to the images location which /usr/local/share/uhd/images

Could you please tell me how to resolve?

**Comment by bastibl** [comment]
This is an issue with your UHD installation. The error suggest to run the program to get new images, not that it cannot find images at all. It'd suggest to just do so and if you still have problems, write to the UHD mailing list.
