### ISSUE TITLE
wifi_rx.grc can not receive the packet from wifi_tx.grc throught air

### ISSUE THREAD

**Issue by kewenkang** [bastibl/gr-ieee802-11#205]
Hi, Bastian
I successfully install gr-ieee802-11. wifi_loopback.grc works well, I can see the packet: "xxx...xx".
wifi_rx.grc can also receive wifi signal from air. When I run wifi_transceiver.grc, I can see the packet, but I don't know the packets are from air or from the tx in wifi_transcevier.grc.
When I run wifi_rx.grc with usrp n210 and run wifi_tx.grc with usrp b210 in the same frequency(5.89GHz or others) and samp_rate(20MHz), wifi_rx can not receive packet from wifi_tx, I didn't see any debug nessage in wifi_rx. I also tune the gain of wifi_rx and wifi_tx, it didn't work. Then I save the output I/Q of wifi_tx to a file sink, and use the same file as the file source of wifi_rx, I can see the packet: "xxx...xx". I don't know why wifi_rx can not receive wifi_tx throught air. 
How can I test whether wifi_tx.grc send the wifi signal?
How can I get throught the communiation from wifi_tx to wifi_rx?
Thanks for your attention.

**Comment by bastibl** [comment]
Great that receiving frames from a WLAN card works. To further debug, you can put the WLAN card in monitor mode and check if it also receives frames form the SDR.
If you want to differentiate between frames from different WLAN transceivers, just change the payload or the MAC adress (or disconnect the frames that you send from the Wireshark sink).
If TX and RX work separately, make sure that you use separate PCs, connect the SDR directly (without switch), don't use a VM, that there are no errors, etc.
