### ISSUE TITLE
what is the output of Wifi MAC decode

### ISSUE THREAD

**Issue by ngatran2018** [bastibl/gr-ieee802-11#207]
Hello,

I pluged the output of WiFi Mac Decode block to a UDP client and send the data to a program, which will process the received data. However, I noticed that the received dta has 24 bytes header attached to the original data that I sent from a transmitter (which is connected to GNU radio via UDP server). Can anyone tell me what is this header?

**Comment by bastibl** [comment]
Its the WLAN MAC header: https://github.com/bastibl/gr-ieee802-11/blob/maint-3.8/lib/utils.h#L34-L42
