### ISSUE TITLE
Buffer too small for min_noutput_items

### ISSUE THREAD

**Issue by sbindel** [bastibl/gr-ieee802-11#210]
Hi Bastian,
During the test of the loopback example, I have observed when I increase the PDU length an error related to the IEEE802.11 chuncks to Symbols block indicating :  
**thread[thread-per-block[10]: <block chunks_to_symbols(7)>]: Buffer too small for min_noutput_items** ,when I use BPSK 1/2 modulation.

However when I used a QAM module the following error appears : 
**<block ofdm_cyclic_prefixer(11)>]: Buffer too small for min_noutput_items**

Is it a problem related to GR_FIXED_BUFFER_SIZE ? Have I to modify buffer of each block ?

__Materials__ : 
* gr-ieee802-11 (maint-3.8)
* gr-foo (maint-3.8)
* GnuRadio 3.8 (Python 3.8.1)
* OS : Archlinux

Best regards

**Comment by sbindel** [comment]
I have set the GR_FIXED_BUFFER_SIZE to 128k, by compiling from the source GNU Radio and it's work.
Is there a way to change the  GR_FIXED_BUFFER_SIZE variable without compile manually ?

**Comment by bastibl** [comment]
Please see this thread and make sure to use the most recent GNU Radio version. https://github.com/bastibl/gr-ieee802-11/issues/190
