### ISSUE TITLE
wifi_phy_hier errors

### ISSUE THREAD

**Issue by msfu101** [bastibl/gr-ieee802-11#211]
hi there,
under Kali Linux and Gnuradio 3.8.0 i built gr-foo and gr-ieee802-11 from Source with no Errors. Then i opened the wifi_phy_hier.grc to build the necessary blocks but i can't build it.
The Error Messages are in the attached file.

![Screenshot from 2020-02-15 06-23-55](https://user-images.githubusercontent.com/51265001/74582446-464b3000-4fbc-11ea-9343-553549afbfea.png)

thanks in advance

**Comment by bastibl** [comment]
Please make sure that the path of the Python modules is in our PYTHONPATH variable. In your case, it seems to be `/usr/local/lib/python3/dist-packages`.

**Comment by msfu101** [comment]
I set the PYTHONPATH Variable and now... it works!
Thank you

**Comment by Cormallonal** [comment]
Hello, I have the same problem. However, I don't know where I can find the PYTHONPATH variable. Could someone briefly explain to me how and where I can find and change them?

**Comment by bastibl** [comment]
Sorry, but how you set an environment variable is not specific to this module and it wouldn't make a lot of sense to explain it the 43.800.001st time. Please google it.
