### ISSUE TITLE
Simple wifi interface test local [Embedded Linux]

### ISSUE THREAD

**Issue by gmartina** [bastibl/gr-ieee802-11#215]
Hello,

Im having some problems with a simple loopback test and I would  appreciate if you help me with some advices. The design is based on your example (but I removed QT and wireshark). I want to test a ping but it doesnt work:

![screen_wifi_test_local](https://user-images.githubusercontent.com/25131607/79451622-1b468200-7fe7-11ea-85a3-93753e0a7688.png)

Hardware: ZynqMP A53
```
root@Raptor:/usr/bin# gnuradio-config-info -v
3.7.13.4
```
ieee80211, foo: maint-3.7
I cross compiled and added everything needed (gnuradio, gr-foo, gr-ieee80211...etc) in my linux image and it looks good.

The wifi_phy_hier module has been generated in my Desktop Linux PC and I copied the files in my embedded linux: /usr/bin
I also generate wifi_loopback_test.grc in my Desktop PC and copy it to my embedded linux.

I run wifi_interface_test_local.py and it starts succesfully. No errors. tap0 created ok.

```
root@Raptor:/usr/bin# python -u wifi_interface_test_local.py
MAPPER: encoding: 0
set_min_output_buffer on block 9 to 397056
set_min_output_buffer on block 11 to 397056
set_min_output_buffer on block 13 to 397056
set_min_output_buffer on block 14 to 397056
set_min_output_buffer on block 16 to 397056
set_min_output_buffer on block 29 to 96000
Allocated virtual ethernet interface: tap0
You must now use ifconfig to set its IP address. E.g.,
  $ sudo ifconfig tap0 192.168.200.1
Be sure to use a different address in the same subnet for each machine.

Press Enter to quit: ether type: IP
ether type: IP
ether type: IP
pdu len 72                  <----- (this starts after ping)
pdu len 190
ether type: IP
pdu len 260
ether type: IP
pdu len 260
ether type: IP
pdu len 260
ether type: IP
```

After that, I config tap0:

```
root@Raptor:~# ifconfig tap0 10.0.10.2 netmask 255.255.0.0
root@Raptor:~#  ip link set dev tap0 mtu 440 
[  814.253072] IPv6: ADDRCONF(NETDEV_CHANGE): tap0: link becomes ready
root@Raptor:~#

root@Raptor:~# ifconfig
eth0      Link encap:Ethernet  HWaddr 00:0a:35:00:22:01
          inet addr:10.0.0.7  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::20a:35ff:fe00:2201/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:857 errors:0 dropped:0 overruns:0 frame:0
          TX packets:853 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:61445 (60.0 KiB)  TX bytes:115987 (113.2 KiB)
          Interrupt:30

tap0      Link encap:Ethernet  HWaddr 9e:69:94:b9:a9:13
          inet addr:10.0.10.2  Bcast:10.0.255.255  Mask:255.255.0.0
          UP BROADCAST RUNNING MULTICAST  MTU:440  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:21 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:4608 (4.5 KiB)

usb0      Link encap:Ethernet  HWaddr ce:3a:3d:ab:b7:11
          inet addr:192.168.1.100  Bcast:192.168.1.255  Mask:255.255.255.0
          UP BROADCAST MULTICAST  MTU:1500  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

root@Raptor:~#
```

```
root@Raptor:~# ping -I tap0 10.0.10.2
PING 10.0.10.2 (10.0.10.2): 56 data bytes

^C--- 10.0.10.2 ping statistics ---
20 packets transmitted, 0 packets received, 100% packet loss
```
As you can see, ping its not working. This design has been tested in a linux Desktop PC, following your instructions, and it works like a charm. But it doesnt in my embedded linux.

 I might think the cause is that the wifi modules are not correctly installed, so the loopback doesnt work. But I get no errors, I have no clue at all.

So I tested python modules to check them out:
```
root@Raptor:~# cd /usr/bin/
root@Raptor:/usr/bin# python
Python 2.7.12 (default, Jun 19 2017, 18:21:12)
[GCC 6.2.1 20161016] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import asdads
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named asdads
>>> import os
>>> import sys
>>> import foo
>>> import ieee802_11
>>> import gnuradio
>>> import wifi_phy_hier
>>> exit()
root@Raptor:/usr/bin#
```

Any idea of what can i test next?

Thank you very much in advance

**Comment by bastibl** [comment]
So the "simple" loopback test is not so simple, when you do not have experience with networking.

First of all, this flowgraph is rather complex to just test loopback. There is a loopback flowgraph that does that without networking.
Also, what do you expect to happen? This is a TAP device talking to itself? If your really want to test networking, use two PCs or create two TAP devices that are connected via GNU Radio.
I doubt that this is supposed to work in the first place. The TAP device would receive frames that are originated from itself. Will these frames even be accepted?
Anyway, the way to debug this further is to use Wireshark to monitor the TAP device.
Also, this is not supposed to be run as root. There is a nic.sh script  in the apps folder that demonstrates how to set it up.

**Comment by gmartina** [comment]
thank you for your answer. I will start in remote mode for the moment.

-Is it possible to make a RF loop back with the same transceiver? (i mean same board, having tx port emitting and rx port receiving,) is it supported by your gnu components? 

- In component WIFI MAC: can you explain the configuration needed to properly connect two transceivers? I mean DST mac,  SRC mac of both of them...

thank you

**Comment by bastibl** [comment]
If you have a radio that supports full-duplex, it's possible. But that's not a feature of the flowgraph or the code. The receiver doesn't know who sent the frame. It will just see a signal and decode it.

The BSSID is ignored and SRC/DST MAC should match SRC/DST Ethernet MAC of SRC/DST.

**Comment by gmartina** [comment]
Thank you!
