### ISSUE TITLE
What's the type of the output from PDU to tagged stream?

### ISSUE THREAD

**Issue by p577665228** [bastibl/gr-ieee802-11#217]
![2020-05-04 23-12-58 的屏幕截图](https://user-images.githubusercontent.com/45257736/80981786-00846200-8e5d-11ea-8961-8d3be7957076.png)

The module PDU to tagged stream will output some IQ data, I'm not sure whether the value of IQ data has been changed or it is the raw IQ data from USRP Source.

**Comment by bastibl** [comment]
The block outputs the equalized constellation points of the data subcarriers.
