### ISSUE TITLE
Invisible in mobile

### ISSUE THREAD

**Issue by Venkyvulpine** [bastibl/gr-ieee802-11#219]
Hi,
The wifi created in router is not visible in mobile Do you know why?

**Comment by bastibl** [comment]
How about adding a little bit of context?

**Comment by Venkyvulpine** [comment]
Hi,
I am using your source code and build transmitter which transmits signal
and it is recieved by reciever (both are routers) but the wifi is not
showing up in mobile which is produced by transmitter router do you know
why it is not working? I have tried changing frequency and bandwidth
according to the mobile.mobile I have used is samsung galaxy s8.

Some of the doubt I have:
1. uhd doesn't have a name so is this impact on visibility.

**Comment by Venkyvulpine** [comment]
Additional information:
We use router as USRP N210

Thanks
Venkatesh

**Comment by Venkyvulpine** [comment]
Why you closed this?

**Comment by bastibl** [comment]
Because there is no way to help you, if you don't manage to formulate a clear question.
