### ISSUE TITLE
usrp uhd device underruns

### ISSUE THREAD

**Issue by Venkyvulpine** [bastibl/gr-ieee802-11#221]
while testing  the device I found that it is actually underrunning 
what is the problem which cause device to underrun

For Your Information:
1. usrp device is directly connected to pc(switch is not used).
2. I am not  using virtual machine.
3.volk_profile  test is succesfull everything is in best state.

![underrun crop](https://user-images.githubusercontent.com/40510883/81803108-d570d100-9534-11ea-9704-86b445ba0fdc.png)

**Comment by bastibl** [comment]
The PC cannot keep up with the data. Try a more powerful PC.

**Comment by Venkyvulpine** [comment]
Thank you for your response!

**Comment by Venkyvulpine** [comment]
Recommended Specification??

**Comment by bastibl** [comment]
There is another issue about the specs. Also you opened another issue about a very related topic. Also there is no information about what you are doing or what hw, etc you are using. I close this.
