### ISSUE TITLE
Problem Wifi_Phy_Hier

### ISSUE THREAD

**Issue by oabravo** [bastibl/gr-ieee802-11#226]
I am having the next problem with the wifi_phy_hier and i can't run it
![Captura de pantalla de 2020-06-14 00-45-52](https://user-images.githubusercontent.com/46819888/84585747-7e327a80-add8-11ea-8351-738ed3c8573e.png)
![Captura de pantalla de 2020-06-14 00-46-55](https://user-images.githubusercontent.com/46819888/84585756-92767780-add8-11ea-8374-667b3ff2a7b4.png)
![Captura de pantalla de 2020-06-14 00-47-22](https://user-images.githubusercontent.com/46819888/84585771-b1750980-add8-11ea-86b6-0f026046e52d.png)
![Captura de pantalla de 2020-06-14 00-48-47](https://user-images.githubusercontent.com/46819888/84585783-d4072280-add8-11ea-9dfa-d17106f4d66c.png)
please i need help

**Comment by bastibl** [comment]
This is very likely because either the python module is not found (it is not in the PYTHONPATH) or the python module cannot find the linked library because it is not in you LD_LIBRARY_PATH. You can open a python console and `import ieee802_11`. This might give more debug output.
Please check the installation instructions and the many issues on the topic.

**Comment by oabravo** [comment]
Python console show me this
But i don't know how solve it, i tried adding the direction /usr/local/lib/python3/dist-package/ to the PYTHONPATH but it didn't work
![Captura de pantalla de 2020-06-15 01-56-28](https://user-images.githubusercontent.com/46819888/84627118-ef8f2d80-aeab-11ea-9c21-e7e23b53bc32.png)

**Comment by bastibl** [comment]
Sorry, but you only provide minimal information. I don't know how or if you installed the module. Let alone where you installed it. You don't write if you actually checked that the files are actually in the folder that you cited. Anyway, since this was discussed in many, many issues. I close this.
