### ISSUE TITLE
Minor question about sync_long and its use of std::list (d_cor)

### ISSUE THREAD

**Issue by hazevt04** [bastibl/gr-ieee802-11#229]
sync_long has a private member, d_cor which is a std::list of std::pairs (one for a complex value and the other for (I presume) the original index of the complex value). 

Later in sync_long::search_frame_start(), d_cor is copied to a std::vector. Why wasn't d_cor originally a std::vector?

**Comment by bastibl** [comment]
puh, I forgot :-) But I think the list is later sorted to search for the three spikes of the cross-correlation. And I think it was easier to sort a list than a vector.
