### ISSUE TITLE
Problem installing GR-Sched

### ISSUE THREAD

**Issue by antondobler** [bastibl/gr-ieee802-11#233]
Dear community,

I have an issue when installing gr-sched. I get an error telling me that 

"include could not find load file grswig"

I am using GRC 3.9 as required and use UHD3.15LTS.

Is there a backward compatibility of GR-Sched for GRC3.7 and 3.8?

Thank you in advance!

BR,
Anton

**Comment by bastibl** [comment]
This is the repository for gr-ieee802-11, not gr-sched. If you have any questions regarding gr-sched, please open an issue in the corresponding repository. Anyways, the gr-sched master branch should be compatible with the master branch of GNU Radio from some months ago, before the pybind11 changes.
