### ISSUE TITLE
gr-ieee802-11 by HackRF

### ISSUE THREAD

**Issue by aler86** [bastibl/gr-ieee802-11#24]
Hello,

i'm trying to use HackRF One in wifi_rx.grc but my output is:

Executing: "/home/alex/gr-ieee802-11/examples/wifi_rx.py"

linux; GNU C++ version 4.8.4; Boost_105400; UHD_003.010.git-80-g777352e7

Using Volk machine: avx2_64_mmx_orc
gr-osmosdr v0.1.4-48-g86ad5842 (0.1.5git) gnuradio 3.7.8.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy 
Using HackRF One with firmware 2014.08.1 
encoding: 1 - length: 2002 - symbols: 446
OOOOOOOOOOOOOOOOencoding: 2 - length: 325 - symbols: 55
OOOOOOOOOOOOOencoding: 1 - length: 3032 - symbols: 675
OOOOencoding: 1 - length: 3306 - symbols: 736
OOOOOOOOOOOOOOOOOOOOOOencoding: 0 - length: 2007 - symbols: 670
OOOOOOOOOOOOOOOOOOOOOOOencoding: 0 - length: 3335 - symbols: 1113
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOencoding: 2 - length: 2202 - symbols: 368
OOOOOOOOOOOOencoding: 3 - length: 601 - symbols: 68
OOOOOencoding: 3 - length: 1177 - symbols: 132
OOOOOOOOOOOOencoding: 5 - length: 1094 - symbols: 61
OOOOOOOOOOOOOOOencoding: 5 - length: 2696 - symbols: 150
OOOOOOOOOOOencoding: 5 - length: 2986 - symbols: 167
OOOOOOOOOOOOOOOOOOOOOOOOOOOOOencoding: 1 - length: 2956 - symbols: 658

ecc ecc.

While wireshark output is:

![wireshark](https://cloud.githubusercontent.com/assets/8875787/11179308/baead104-8c52-11e5-94c8-9eb0ffb90631.png)

Can you help me, please.

Thanks in Advance

**Comment by bastibl** [comment]
The 'O's indicate that samples had to be dropped since your PC could not handle them fast enough.

Use volk_profile to assert that you are using the fastest SIMD implementations for your architecture. If that doesn't help you have to decrease the sample rate or get a faster PC.
