### ISSUE TITLE
Is there Doxygen-generated manual included?

### ISSUE THREAD

**Issue by YunxiangCai** [bastibl/gr-ieee802-11#247]
It's a piece of wonderful work! I wander if there is any Doxygen-generated manual that describe the APIs or process of DSP for each block? Thanks!

**Comment by bastibl** [comment]
There is, unfortunately, no Doxygen documentation at the moment.  There is  a description of most blocks in my thesis https://www.bastibl.net/bib/bloessl2018physical/bloessl2018physical.pdf (Chapter 4). Maybe that helps a bit to understand what's going on.

**Comment by YunxiangCai** [comment]
Thanks a lot! :)
