### ISSUE TITLE
Problem with the wifi_loopback

### ISSUE THREAD

**Issue by Bricko44** [bastibl/gr-ieee802-11#249]
Hello, 
I have a problem with the use of GNURadio and the ieee802_11 module.

After having had big installation problems (especially because of thrift), I think I installed GR38 correctly.
For information my environment is GR38 (maint-3.8), Ubuntu 20.04, Thrift 0.13.0.
I installed GR38 from github repository, also gr-ieee802_11.

I started by compiling the wifi_phy_hier in my test folder. After generating the file and running it, I don't see any errors.
Following that, I followed the bastibl guide, and started the wifi_loopback program. No errors during compilation, but when launching the program I get the following errors :

`Generating: '/home/hugo/gr-ieee802-11/examples/wifi_loopback.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python3 -u /home/hugo/gr-ieee802-11/examples/wifi_loopback.py

QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
MAPPER: encoding: 0
set_min_output_buffer on block 5 to 207744
set_min_output_buffer on block 3 to 2077440
set_min_output_buffer on block 5 to 2077440
set_min_output_buffer on block 6 to 207744
set_min_output_buffer on block 7 to 415488
set_min_output_buffer on block 8 to 207744
Could not find port: out in:
system

Traceback (most recent call last):
  File "/home/hugo/gr-ieee802-11/examples/wifi_loopback.py", line 345, in <module>
    main()
  File "/home/hugo/gr-ieee802-11/examples/wifi_loopback.py", line 320, in main
    tb = top_block_cls()
  File "/home/hugo/gr-ieee802-11/examples/wifi_loopback.py", line 164, in __init__
    self.wifi_phy_hier_0 = wifi_phy_hier(
  File "/root/.grc_gnuradio/wifi_phy_hier.py", line 90, in __init__
    self.msg_connect((self.ieee802_11_decode_mac_0, 'out'), (self, 'mac_out'))
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 60, in wrapped
    func(self, src.to_basic_block(), srcport, dst.to_basic_block(), dstport)
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 132, in msg_connect
    self.primitive_msg_connect(*args)
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/runtime_swig.py", line 3006, in primitive_msg_connect
    return _runtime_swig.hier_block2_sptr_primitive_msg_connect(self, *args)
RuntimeError: invalid msg port in connect() or disconnect()`

Can you explain to me what I'm doing wrong? I am new to using GNURadio, it is possible that I forgot to do something.
Thank you in advance.
Hugo

**Comment by bastibl** [comment]
why does the flowgraph (from your user's home) use the hierblock from `/root`? And why does it have access to that? Don't start GNU Radio as `root`. I assume this is an artifact from previous attempts. Start GRC as user, open and build the hier block, start the loopback flowgraph.

**Comment by Bricko44** [comment]
I did indeed run GRC as root, "by default". I will try without.

When installing my GR38, I did not specify an installation path for the software, because I wanted to adjust my PYTHONPATH subsequently. Therefore, I do not know why, but my GRC is installed in / usr / local / bin instead of / usr / bin. I am therefore obliged to move to the local folder, in order to start grc via ./gnuradio-companion.

I will try to run GRC using the user "hugo". Do I need to save the hier block on a folder in my /home/hugo/gr-ieee802-11 or in a specially created folder? Same question for the loopback ?

Thanks,
Hugo

**Comment by bastibl** [comment]
If you don't specify an installation path with `-DCMAKE_INSTALL_PREFIX=...`, GNU Radio will use `/usr/local/` by default. This is as intended, since `/usr/` is used by your distribution's package manager and manually installed software shouldn't interfere with that.

Your shell will use all directories in your `PATH` variable to search for executables, i.e., `/usr/local/bin` is not in your path. If you want this, just add it.

It's not clear to me, if you do this, but since it sounded like it: do not "move" the GNU Radio directories after they are installed. Instead, adjust your various path variables accordingly.

When you build a hier block, it will be stored in `${HOME}/.grc_gnuradio`. If you run it as user, it will be `/home/hugo/.grc_gnuradio`. If you run it as root, it will be `/root/.grc_gnuradio`. This is, however, only the case for hier blocks (the ones that show up as blocks in GRC after they are compiled). Flowgraphs will just create a corresponding `.py` file in the directory of the flowgraph.

**Comment by Bricko44** [comment]
I just tried to make it work from user instead of root. I get the same error : 

`Generating: '/tmp/wifi_loopback.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python3 -u /tmp/wifi_loopback.py

MAPPER: encoding: 0
set_min_output_buffer on block 5 to 207744
set_min_output_buffer on block 3 to 2077440
set_min_output_buffer on block 5 to 2077440
set_min_output_buffer on block 6 to 207744
set_min_output_buffer on block 7 to 415488
set_min_output_buffer on block 8 to 207744
Could not find port: out in:
system

Traceback (most recent call last):
  File "/tmp/wifi_loopback.py", line 345, in <module>
    main()
  File "/tmp/wifi_loopback.py", line 320, in main
    tb = top_block_cls()
  File "/tmp/wifi_loopback.py", line 164, in __init__
    self.wifi_phy_hier_0 = wifi_phy_hier(
  File "/home/hugo/.grc_gnuradio/wifi_phy_hier.py", line 90, in __init__
    self.msg_connect((self.ieee802_11_decode_mac_0, 'out'), (self, 'mac_out'))
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 60, in wrapped
    func(self, src.to_basic_block(), srcport, dst.to_basic_block(), dstport)
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/hier_block2.py", line 132, in msg_connect
    self.primitive_msg_connect(*args)
  File "/usr/local/lib/python3/dist-packages/gnuradio/gr/runtime_swig.py", line 3006, in primitive_msg_connect
    return _runtime_swig.hier_block2_sptr_primitive_msg_connect(self, *args)
RuntimeError: invalid msg port in connect() or disconnect()

>>> Done (return code 1)`

**Comment by Bricko44** [comment]
For information, it actually Works Now !!! 

I uninstalled and re-installed gr-ieee802. I just thinked that i've done a lot of change recently, so maybe some packages where misplaced. After re-installation, i finally see the constellation !

Thanks for your help. Using the user instead of root was not in my head.
