### ISSUE TITLE
Problem Latency with gr-802.11

### ISSUE THREAD

**Issue by aler86** [bastibl/gr-ieee802-11#25]
Hi Bastian,

How can i manage the latency between pc and my hardware?

Do i need another hardware or software?

Thanks a lot

**Comment by bastibl** [comment]
Hi, could you please be a little bit more verbose. I don't really get what you are aiming for.

If it's about the delay between your PC and the SDR there is not much you can do. If you have tough latency requirements you might want to look into FPGA-based architectures like WARP or Ettus' RFNOC.
