### ISSUE TITLE
WiFi_tx.grc with hackrf does not receive frames as malformed.

### ISSUE THREAD

**Issue by pierregalant** [bastibl/gr-ieee802-11#252]
Hello,
Now that we can transmit over air with the hackrf, I would like to receive the signal with another hackrf. However, wifi_tx  does not receive frames correctly. I have replaced the USRP block with the osmocom block and I have added wireshark blocks to view data in wireshark (see below)

1. It does not receive the same amount as on wireshark running on another pc under monitor mode
2. All received packets are malformed
3. Same observation whether transmitted data are beacons created using scapy or data frames created by the message strobe block

I have also tried to connect the two hackrf via a RF cable, I observe same problems.

Upon addition of some blocks, the wifi_tx.grc works fine when the transmission and reception is done in the same chain without using a hackrf, that is in a loopback: UDP -> TRANSMITTER -> RECEIVER

![wifiRXhackrf2](https://user-images.githubusercontent.com/77594215/106923220-c276e000-6705-11eb-946c-a35eb52cbfed.png)

**Comment by bastibl** [comment]
When you want to do performance measurements, the HackRF is probably not the right tool. It works (in the sense that you can receive some frames), but it won't be as reliable as your WLAN card. You'd need a more expensive SDR.

Anyway, the HackRF has DC offset that is not compensated by the HW or the driver. That means, there is a spike in the center. This will mess with WLAN frame detection (it will trigger all the time and overload the PC). You'd have to add a filter for this spike right after the source. I created an adapted flowgraph some time back:
https://github.com/bastibl/instant-gnuradio/blob/wlpc/assets/wifi_rx.grc

I just added some filter that made it work to some extend. It might be too relaxed or too narrow. I didn't try to optimize it.
