### ISSUE TITLE
abnormal peaks

### ISSUE THREAD

**Issue by ENB213-xiaoh** [bastibl/gr-ieee802-11#256]
Hi Bastian. I'm trying to use your tool to measure the carrier frequency offset. Before that, I tried to reproduce the experiments shown in your paper <An IEEE 802.11a/g/p OFDM Receiver for GNU Radio>. But I get sort of weird results. I'm using N210.

For example, this image detects the frame start by correlation. The peak=1 are the beacon frames and it makes sense since there are about 2M samples between each two as the beacon interval is 102ms. However, there are some other peaks, and the rest values are all large, which is abnormal. I'm sure there are no other frames except beacons because the LTF detection is correct and it shows three frames. So, I'm wondering why these abnormal peaks and high corr-values exist. Please kindly advise. Data are collected using sink block.

![Capture](https://user-images.githubusercontent.com/57006632/108803057-f7cd5b80-7556-11eb-9eb1-04be92153252.PNG)

**Comment by bastibl** [comment]
This seems to be an uncompensated DC offset. The USRP source should have an option to filter it out.

**Comment by ENB213-xiaoh** [comment]
Yes. Thanks. I have cleaned out the DC offset. I have to update my gnuradio because it seems the old version is not able to enable it automatically.
