### ISSUE TITLE
Based on the receiver, how to separate the packet data from the whole received data?

### ISSUE THREAD

**Issue by YunxiangCai** [bastibl/gr-ieee802-11#257]
[1] refers that the the process of the receiver can be divided into two stage: Frame Detection and Frame Decoding. After frame Detection, the packet can be separated from the received data. But when I add a file sink after the OFDM Sync Long moudle, I found the separated data is not exactly the packet. So how could I separate the packet(including signal filed and data field) from the received data?

[1] Bloessl B, Segata M, Sommer C, et al. An IEEE 802.11 a/g/p OFDM Receiver for GNU Radio[C]//Proceedings of the second workshop on Software radio implementation forum. 2013: 9-16.

**Comment by YunxiangCai** [comment]
<img width="264" alt="image" src="https://user-images.githubusercontent.com/37821095/109107673-1efd7600-776d-11eb-8b2e-9ce56f309fd4.png">

I add a file sink before FFT. But seems that the signal is not the pure packet data.

**Comment by bastibl** [comment]
I'm not sure what exactly you were expecting. You sent the signal over the air. It is of course not a 1-to-1 equivalent of the IQ data that you produced.
In case you wonder about the length: The frame detection just recognizes a frame start. It doesn't know where it ends. So it just forwards data according to a max sized frame into the flowgraph.

**Comment by YunxiangCai** [comment]
Thanks for your reply. Sorry for my poor English. I add a diagram to explain it:

<img width="698" alt="Screen Shot 2021-02-25 at 2 59 56 PM" src="https://user-images.githubusercontent.com/37821095/109115510-28410f80-777a-11eb-83b8-b78d45cb7218.png">

The received data from USRP is massive but not all data contains information. When there is no packet, there is no information, so I want to extract the data that contains a packet.

**WIFI Sync Short** moudle and **WIFI Sync Long** moudle play a role to detect a packet and forward the packet data to Frame decoding. I wonder if it can be done with the receiver.  

I have tried to add a file sink before FFT:
![image](https://user-images.githubusercontent.com/37821095/109116336-53782e80-777b-11eb-9ea1-936f3631132b.png)

**Comment by bastibl** [comment]
As I said: The frame detection just recognizes a frame start. It doesn't know where it ends. So it just forwards data corresponding to a max sized frame into the flowgraph. Your frame is shorter, which is why you see these gaps.
The normal flowgraph, will learn form the signal field, how long the frame is an drop the rest. If you want to remove the gaps, you'd have to add this functionality yourself. Depending on your goal/scenarios, it might be enough to just add a threshold.

**Comment by YunxiangCai** [comment]
Thanks a lot. It works.
