### ISSUE TITLE
Correlation Output Initialization?

### ISSUE THREAD

**Issue by bkihei** [bastibl/gr-ieee802-11#26]
I noticed that the **autocorrelation output** in the receiver chain appears to have an initialization phase (oscillator stabilization?) that expands above .56, and doesn't settle until about 1e7 samples. The other high spikes are packets that were being detected from a COTS 802.11p radio.

![correlationoutput](https://cloud.githubusercontent.com/assets/16578866/12147690/3bf17b26-b468-11e5-8250-b614f50e92cd.png)

I added some code to ofdm_sync_short.cc to tell me when initialization was complete before the search state was entered. I'm interested to see if anyone else thinks this would be useful. This just makes sure that the initialization phase is complete before the receiver starts detecting packets.
```c++
/*This is the first state when the flowgraph starts. 
It is never entered into again, once it transitions the receiver to the SEARCH state.*/
case INIT: {
			int k;
			for(k = 0; k < ninput_items[2]; k++) {
				d_initSamples++;
/*the autocorrelation value must be low, and 1e7 must have been received 
since starting the flow graph.*/
				if(in_cor[k] < d_threshold && d_initSamples > 1e7) {
					dout << "Initialization complete!" << std::endl;
					d_state = SEARCH;
					d_initSamples = 0;
					break;
				}
			}
			consume_each(k);
			return 0;
		} 
```
I was surprised that this initialization phase is captured by the autocorrelation output, which prompted me to add this code to my build. The code is very helpful. 

The values for d_threshold, d_initSamples, and the GAIN in the flow graph may need to be adjusted depending on each users set-up, perhaps 1e7 could be a block parameter which states how many samples must have been received from the device since the flowgraph has started. This should also be turned off if users are not using an SDR, because this INIT state is not needed for simulations.

**Comment by bastibl** [comment]
AFAIK, this is since the DC offset compensation needs some time to get a good estimate for the mean. During that time the DC component triggers frame detection due to its autocorrelation. That should not be much of a problem, but only cause some false positives in the beginning.

If you want to avoid that, you can just skip the first n samples with the Head block of GNU Radio.

**Comment by bkihei** [comment]
Thanks so much for the reply. The Skip Head block worked perfectly.

**Comment by bastibl** [comment]
great!
