### ISSUE TITLE
When the usrp N210 is powered off, the module parse_mac still has output for serveral minutes

### ISSUE THREAD

**Issue by xiaolingu** [bastibl/gr-ieee802-11#261]
Hi, 
I have some questions to ask for you help. I modify the parse_mac.c to write the some information of received frame into a file.  The serveral 'D' displayed in the terminal but it seems that the project gr-ieee802-11 still runs normally. However when I power off the USRP N210, the some information of received frame is still written into the file above for serveral minutes. I am sure that these written information is right. Because I want to get approximate timestamp of every received frame which is captured by the USRP N210. However the latency disrupts the timestamp of every frame received in the USRP. Do you have any suggestions on the above issues ? I am looking forward to your reply.

**Comment by bastibl** [comment]
The 'D's indicate that your PC didn't process the sample stream from the SDR fast enough and had to drop samples. This won't crash the receiver but will leads to dropped frames, if the dropped samples were part of a frame. I assume that the problem that the receiver still writes data minutes after the USRP is shutdown doesn't happen with the unmodified version, does it? In this case there is some bug in your modification (probably with consuming data).
Regarding timestamps, you can get approx. ms accuracy if you timestamp at the decoder. If you need higher accuracy, you have to
- make sure that no samples are dropped (no 'D's)
- consider using an external clock signal if the oscillator is not stable enough for your use-case
-  modify sync short to annotate the absolute sample number of the sample where the frame starts (`n_items_read`). This information has to propagated downstream with item tags, similar to how it's done for the frequency offset.
