### ISSUE TITLE
Wifi and HackRF.

### ISSUE THREAD

**Issue by josephcab** [bastibl/gr-ieee802-11#264]
Hi,
I'm actually doing a research work, and I have some problems to use the wifi_rx (and also the wifi_tx) files. I'm using :

- gnuradio 3.8
- Ubuntu 20.04
- HackRF SDR.

I have seen that this SDR was not particularly recommended to done some work around Wifi. Have you some recommendation about that ? (and particularly for SDR compliant with the gnuradio USRP blocks) ?

Anywhere, when i using the wifi_rx script with hackRF, I can only get a lot of 
`gr::log :INFO: sync_long0 - LONG: frame start at 320`
Have you an explanation or an idea of solution for solving this problem ?

Thanks a lot per advance for your response.
I'm available if you need more details. Just below a screenshoot of my gnuradio adaptation of your script.

![script](https://user-images.githubusercontent.com/11904578/112972173-3fe02f00-9150-11eb-8862-e65ef752742e.png)

**Comment by bastibl** [comment]
Yes, the HackRF has an uncompensated DC offset. As mentioned in the other issues about the topic, use the adapted flowgraph, which adds a filter after the SDR. This adds some computational overhead, but you might be able to optimize the filter.  If you consider buying another SDR, you could have a look at the Ettus B2XX series.
