### ISSUE TITLE
#wifi_transceiver.grc

### ISSUE THREAD

**Issue by Joeyue68** [bastibl/gr-ieee802-11#267]
Hey!
I used  USRP B210 as device. But when I attempted to generate wifi_transceiver.grc, the red light on the TXRX port, which was on the device, didn't glint. It seemed that I could receive the signal, but I couldn't transmit signal into air from B210. I wonder where the bug is. And whether there is some problem on my device or .grc. Plus, I could trasmit signal when I generate the wifi_tx.grc. This  truly bothers me. I'd appreciate it if you happen to know how to fix it!

**Comment by zsy9512** [comment]
You can try to add your tx_gain

**Comment by Joeyue68** [comment]
> You can try to add your tx_gain

Could you be more specific? Should I add a block in my wifi_transceiver.grc?

**Comment by bastibl** [comment]
The frames are so short that you probably won't see the LED turning on. What exactly is your issue and setup? How do you know that it doesn't work etc.

**Comment by Joeyue68** [comment]
/home/berk/桌面/1.png
/home/berk/桌面/2.png
These might be the problems, do you know how to fix them?

**Comment by Joeyue68** [comment]
![1](https://user-images.githubusercontent.com/57308095/115598373-eb723e80-a30c-11eb-9871-cb30841a7008.png)
![2](https://user-images.githubusercontent.com/57308095/115598421-ffb63b80-a30c-11eb-9741-9dcf35459161.png)
These seem to be the issues, could you help with that?

**Comment by bastibl** [comment]
That's an issue of the GNU Radio QT GUI Sink and not of this module. Please write to the GNU Radio mailing list, ask in the Matrix chat, or open an issue at the GNU Radio repo.
