### ISSUE TITLE
Error: thread[thread-per-block[16]: <block frame_equalizer (8)>]: block::general_work() not implemented

### ISSUE THREAD

**Issue by egoistzty** [bastibl/gr-ieee802-11#270]
Dear bastibl,
Sorry for disturbing you again. I want to modify some blocks, but as I am a beginner in gnuradio, there are some problems I can't understand.
The main purpose is to pass the csi data (already exposed in the frame_equalizer block), to the decode_mac block, so I can screen the csi by mac address. So I decide to add another io stream between these two blocks as the following flowgraph:

![NJME}REZFQYZDN E850G90K](https://user-images.githubusercontent.com/44116484/116174360-d51b1700-a740-11eb-800f-0b27c3542cfb.png)

And the code is modified correspondingly:
`frame_equalizer_impl::frame_equalizer_impl(Equalizer algo, double freq, double bw, bool log, bool debug):`
`gr::block("frame_equalizer", `
`gr::io_signature::make(1, 1, 64 * sizeof(gr_complex)),`
**`gr::io_signature::make2(1, 2, 48, 52 * sizeof(gr_complex)) ),`**

`frame_equalizer_impl::general_work (`
**`gr_vector_int &noutput_items,`**
...
`const gr_complex *in = (const gr_complex *) input_items[0];`
`uint8_t *out = (uint8_t *) output_items[0];`
**`gr_complex *= (gr_complex *) output_items[1]; `**

I try to let the noutput_items[0] be the number of the uint8_t symbols, and noutput_items[1] be the number of gr_complex csi
and I recompile file without any bug, but when I execute the flowgraph in gnuradio, the following error appeared:

**_thread[thread-per-block[16]: <block frame_equalizer (8)>]: block::general_work() not implemented_**

Did I use the io_signature in a wrong way? And can you tell me how to realize the goal of passing two types data from one block to another? I would be appreciate it.

**Comment by bastibl** [comment]
The error seems to indicate that you changed the signature of the general_work function. It is no longer implemented/overwritten in your block and the implementation of the base class raises this error.
If you have similar errors, it would be great, if you could write to the GNU Radio mailing list or ask the question in the GNU Radio matrix chat, since this is not directly related to this module but a general GNU Radio/C++ question.
