### ISSUE TITLE
problem of wifi_rx.grc

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#272]
hello, my English is poor, so please ignore my grammar problems. I have two questions
1. Why I open the captured data packets with Wireshark, some of which are not 802.11 protocol, and why I can't  receive the beacon frame or probe frame sent by the mobile phone in the 2.4G frequency band?

**Comment by lms7657061** [comment]
well, thank you very much! I have correctly received and demodulated the frame.

**Comment by lms7657061** [comment]
well, thank you very much! I have correctly received and demodulated the frame.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bastibl/gr-ieee802-11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月25日(星期二) 下午3:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bastibl/gr-ieee802-11] problem of wifi_rx.grc (#272)





 
Can you please add much, much more information. For example, what frames you see and what exactly you're doing to receive beacons on 2.4GHz? Also, I'd suggest starting with 11a on 5GHz to rule out potential issues with unsupported frames on 2.4GHz (11b and compatibility modes).

**Comment by lms7657061** [comment]
by the way, in the sync_short.cc file, whether the d_freq_offset is the coarse carrier frequency offset of the frame? in the sync_long.cc file ,whether the d_freq_offset is the fine carrier frequency offset of the frame? and how to print them?
sorry, I can't put the code picture in here.

**Comment by bastibl** [comment]
great that it worked. The estimation in sync short is not as precise as the one in sync long. So you might call it coarse and fine. You can print variables with `std::cout << var << std::endl;`.
