### ISSUE TITLE
Rftap option not displaying on wireshark

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#273]
Hello,
Jonathan Brucker added RFtap support to some of your OOT modules. RFtap bridges the gap between SDR transceivers and network monitors like Wireshark. I have installed gnuradio through sudo apt-get and rftap through source as mentioned on site.
When I lauch wireshark I am not able to see any options of rftap in wireshark. There is some problem with installation.Is there any step i am missing? Thank you!

**Comment by bastibl** [comment]
I'm afraid I cannot help you with this. I use Wireshark through the blocks in the example flowgraphs. AFAIS, this is a question/issue for gr-rftap and not this module.
