### ISSUE TITLE
the frequency offset in the wifi_rx

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#274]
hello! I have a question of the frequency offset of the wifi.rx, why I add std::cout <<"freq_offset:"<< d_freq_offset << std::endl; in sync_short.cc and sync_long.cc, but there aren't noting print in the terminal?
![image](https://user-images.githubusercontent.com/49738399/119828556-dd779500-bf2c-11eb-86c9-2fa131794be2.png)
![image](https://user-images.githubusercontent.com/49738399/119828607-e8cac080-bf2c-11eb-966e-d7e92640c42b.png)

**Comment by bastibl** [comment]
Because you put the prints at points in the code that should not be reached (the first is just before an exception) or are unlikely to be reached (second case).
