### ISSUE TITLE
Ask question of the carrier frequency offset of the frame

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#275]
hello, sorry to bother you again!  In the sync_long.cc, there are d_freq_offset, in the frame_equalizer_impl.cc, there are d_freq_offset_from_synclong, but they have different values, why? and which one is the carrier frequency offset?
![image](https://user-images.githubusercontent.com/49738399/119987144-488d9e00-bff7-11eb-873f-6814d91e48b0.png)
![image](https://user-images.githubusercontent.com/49738399/119987165-4e837f00-bff7-11eb-92cf-9a9afef9795f.png)

**Comment by bastibl** [comment]
Sync short estimates the frequency offset, compensates for it, and annotates the estimate to tell downstream blocks how much it compensated. Sync long does another compensation based on more data and annotates the overall frequency offset (compensation of sync short + sync long), which is extracted in the equalizer. I'd assume `d_freq_offset_from_synclong` is what you are looking for.

**Comment by lms7657061** [comment]
Ok，I get it, thank you very much!
