### ISSUE TITLE
Ask the MAC address of the frame

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#276]
hello! I have a question of the mac address of the probe request frame. I can receive the probe request which from my mobile phone, but the mac address isn't my mobile phone mac address, why?  If it can use the randomization of MAC addresses to explain it, why the mac address keep same all the receive time?

**Comment by bastibl** [comment]
Probe request are used for active scanning, which is done periodically. This mechanism often uses random MACs to make tracking harder. Once the device notices that it is in range of the AP, it will connect to it with its real MAC.
