### ISSUE TITLE
gr-ieee802-11 is missing the Pybombs recipe file. 

### ISSUE THREAD

**Issue by dansharp23** [bastibl/gr-ieee802-11#281]
I was successful in installing the gr-foo module through pybombs. After following the same process that I used for gr-foo I get the following error. 

[ERROR] Error fetching recipe `gr-ieee802-11':
Package gr-ieee802-11 has no recipe file!

I may be mistaken but judging from other issues it seems others have been successful installing this module through pybombs. Thank you in advance.

**Comment by bastibl** [comment]
Please see my reply here: https://github.com/bastibl/gr-ieee802-11/issues/238#issuecomment-860029696.
