### ISSUE TITLE
Ask question of snr in the frame_equalizer_impl.cc

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#286]
hello! I want to ask a question of snr in the frame_equalizer_impl.cc,
![Uploading image.png…]()
as we can see in the picture, the frequency offset is from wifi sync long, so I want to ask whether or not the snr is also from the  wifi sync long?  or the snr is from the whole frame?
sorry for my poor English, I don't know how to explain. Thank you!

**Comment by bastibl** [comment]
The SNR is estimated from the long training sequence in the Equalizer.
