### ISSUE TITLE
Ask question of the frequency offset estimation

### ISSUE THREAD

**Issue by lms7657061** [bastibl/gr-ieee802-11#290]
hi, I have a question of the frequency offset estimation
![Uploading image.png…]()
![Uploading image.png…]()
as we can see in the two picture. In the sync_short.cc, the const pmt::pmt_t value = pmt::from_double(freq_offset); but why in the sync_long.cc, the pmt::from_double(d_freq_offset_short - d_freq_offset)?  in the sync_long.cc, why not this one: pmt::from_double( d_freq_offset)?
can you explain why? thank you!

**Comment by bastibl** [comment]
The upload of the pictures didn't work.

The Sync Short block does a first, more coarse estimation of the frequency offset and already compensates for it. This means the Sync Long block already sees a frame with a (partially) compensated frequency offset. It does another, more fine grained estimation and also compensates for it. The downstream blocks see the signal with both compensations applied. The part of the code, you cited, annotates the overall frequency offset to downstream blocks.
