### ISSUE TITLE
Wrong PDU cpatured by wireshark

### ISSUE THREAD

**Issue by YunxiangCai** [bastibl/gr-ieee802-11#291]
Hi, sorry to bother you again.

I have implemented the wifi_rx.grc successfully. But when I use wireshark to see the content of the received packets, I find that the PDU contents are wrong. But the constellation seems to be perfect. I don't know why. 

What I have done:
mkfifo /tmp/wifi.pcap
python3 wifi_rx.py
wireshark -i /tmp/wifi.pcap   （I use -i instead of -k beacause of warning)

![WeChat Image_20210630222126](https://user-images.githubusercontent.com/37821095/123977437-911ee980-d9f1-11eb-9672-164a8b67208c.jpg)

My Environment:
Ubuntu 18.04
GNU Radio 3.8
USRP N210 as receiver
arada DSRC (802.11p) as a transmitter
freq=channel 178 | 5.89GHz
lo_offset = 11e6  (Actually I don't know how to choose this value)
sample rate = 10MHz

Looking forward to your reply.

**Comment by bastibl** [comment]
Looks perfectly fine to me. The data only reaches Wireshark if it passes the CRC. I'd assume that this is exactly what the transmitter sends.
