### ISSUE TITLE
grcc: error: unrecognized arguments: -d

### ISSUE THREAD

**Issue by wzy0108** [bastibl/gr-ieee802-11#297]
In the /gr-ieee802-11-maint-3.8/simulations/sensitivity,   I use the command make，it shows 
`grcc -d . sim.grc
usage: grcc [-h] [-o DIR] [-u] [-r] GRC_FILE [GRC_FILE ...]
grcc: error: unrecognized arguments: -d
Makefile:13: recipe for target 'sim.py' failed
make: *** [sim.py] Error 2`

**Comment by bastibl** [comment]
They changed the `-d` option to `-o`.

```
basti@thrang ~ >> grcc -h
usage: grcc [-h] [-o DIR] [-u] [-r] GRC_FILE [GRC_FILE ...]

Compile a GRC file (.grc) into a GNU Radio Python program and run it.

positional arguments:
  GRC_FILE              .grc file to compile

optional arguments:
  -h, --help            show this help message and exit
  -o DIR, --output DIR  Output directory for compiled program [default=.]
  -u, --user-lib-dir    Output to default hier_block library (overwrites -o)
  -r, --run             Run the program after compiling [default=False]
```

Once you get it working, a PR with a fix would be appreciated.
