### ISSUE TITLE
About WiFi packet transmission time

### ISSUE THREAD

**Issue by Leoplt** [bastibl/gr-ieee802-11#305]
Hello, In example wifi_tx.grc  ,  I want to know whether the duration of WiFi packets during transmission can be controlled through existing parameters (e.g. samp_rate, pdu_length, interval)?
Thank you for your attention and look forward to your reply！！

**Comment by bastibl** [comment]
You can increase the PDU lenght, i.e., add more payload to make the frame longer. Also changing the Encoding makes the frame longer (BPSK 1/2 results in the longest frames).

**Comment by Leoplt** [comment]
Thank you for your reply!
I want to get the transmission time of each WiFi frame.
How to calculate the transmission duration of each WiFi frame？

**Comment by bastibl** [comment]
It's non-trivial calculation that I'd also had to look-up in the standard. You could create the frame with this module and see in how many samples it results but that's a bit overkill. In general it it is: 2 symbols short preamble + 2 symbols long preamble + 1 symbol signal + X symbols for the payload, which depends on the MCS.
