### ISSUE TITLE
About automatic adjustment of transmission power

### ISSUE THREAD

**Issue by lrisd** [bastibl/gr-ieee802-11#308]
Hello
I want to automatically adjust the transmit power instead of dragging it manually
How can I achieve it ?

**Comment by bastibl** [comment]
GRC generates a Python script from the  flowgraph. You can modify this script to change the gain periodically. Alternatively, you can create a GNU Radio block that emits messages with UHD commands and connect the output of this block to the UHD block. See here: https://www.gnuradio.org/doc/doxygen/page_uhd.html
