### ISSUE TITLE
some problems when installing gr-foo

### ISSUE THREAD

**Issue by GladToLovelyj** [bastibl/gr-ieee802-11#31]
Hi,thanks for this wonderful project! But i have some problems when i installed the gr-foo in the step"make",it shows as follows:
`Linking CXX executable foo_swig_swig_2d0df
Swig source
/home/loveyan/gr-foo/swig/foo_swig.i:3: Error: Unable to find 'gnuradio.i'
swig/CMakeFiles/foo_swig_swig_2d0df.dir/build.make:97: recipe for target 'swig/foo_swig_swig_2d0df' failed
make[2]: *** [swig/foo_swig_swig_2d0df] Error 1
CMakeFiles/Makefile2:286: recipe for target 'swig/CMakeFiles/foo_swig_swig_2d0df.dir/all' failed
make[1]: *** [swig/CMakeFiles/foo_swig_swig_2d0df.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
`
I'm looking forward to your help,thank you very much!

**Comment by bastibl** [comment]
Looks like you GNU Radio installation is broken. You could try installing another OOT module. I guess they will fail too.

**Comment by GladToLovelyj** [comment]
Thank you very much! I have successfully installed GNU Radio 3.7.8 before this with some warnings.
Could you tell me how to solve this problem?
thanks for your reply!

**Comment by bastibl** [comment]
Please see the GNU Radio Wiki:
http://gnuradio.org/redmine/projects/gnuradio/wiki/InstallingGR
If you still have problems you can ask for help on the mailing list. (If you write to the list, you should consider actually mentioning the warnings that you got.)

**Comment by GladToLovelyj** [comment]
Thank you! I have reinstalled the GNU Radio3.7.8,and this problem has been solved.But now when I open wifi_phy_hier.grc,some blocks missed.It's as follows:
![2016-03-30 22-44-47](https://cloud.githubusercontent.com/assets/12248731/14146148/37bafaac-f6c9-11e5-91d8-8d286599d6ca.png)
![2016-03-30 22-44-51](https://cloud.githubusercontent.com/assets/12248731/14146153/393d94ac-f6c9-11e5-83f3-d5d15d340f1d.png)

**Comment by bastibl** [comment]
Please read the readme
https://github.com/bastibl/gr-ieee802-11#check-message-port-connections
