### ISSUE TITLE
HackRF one Receiving/Transmitting ITS-G5 using wifi_rx/tx

### ISSUE THREAD

**Issue by YamanDaif** [bastibl/gr-ieee802-11#311]
Hi Bastian! I'm using [wifi_rx.grc](https://github.com/bastibl/instant-gnuradio/blob/wlpc/assets/wifi_rx.grc) flowgraph you uploaded for the hackrf.
When trying to receiving test packages from Cohda wireless mk2 the output is : 
"
Ogr::log :INFO: sync_long0 - LONG: frame start at 320
Ogr::log :INFO: sync_long0 - LONG: frame start at 320
gr::log :INFO: sync_long0 - LONG: frame start at 320
:
gr::log :INFO: sync_long0 - LONG: frame start at 320"
and the file wifi.pcap is only 24byte and empty when I open it with Wireshark. 
As I read from earlier issues you assisted this might be an off-set but since I'm using the exact same flowgraph you uploaded for the hackrf, I can't come up with any other reason causing this.

When transmitting from the hacker, the output on the gnu radio is "UUUU..." and the Cohda wireless boxes doesn't detect anything. As I understood from earlier issues this could be an underflow, but with my little experience with GNU radio, I can't really spot the blocks that are causing this issue (if it is even an underflow). For transmitting, I'm using the wifi_tx.grc file and changed only the sink to (Osmocom sink) for HackRF as seen in the attached figure.

Here you can find [wifi_rx.grcl](https://github.com/YamanDaif/gr-ieee802-11/blob/maint-3.7/examples/wifi_rx.grc) and [wifi_tx.grc](https://github.com/YamanDaif/gr-ieee802-11/blob/maint-3.7/examples/wifi_tx.grc) that I'm using with HackRF one. 

The help with tracking down the problem I'm having with my setup would be much appreciated! 

I'm are using GNU Radio Companion 3.7.9 installed on Ubuntu 16.04 persistent live USB.
PS. wifi_loopback.grc works fine without any problems.

![GNU - 1](https://user-images.githubusercontent.com/66362955/135896296-ed0fb383-cbc9-4423-8b0a-df6a4b8e79f0.png)

**Comment by bastibl** [comment]
It is OK if there is one underrund (i.e., one "U" per frame) since the HackRF doesn't now that the frame ended and thinks it is an underrun. Also, you are using a sample rate of 1MHz, but IEEE 802.11p uses 10MHz.

**Comment by YamanDaif** [comment]
How do I know if it's "one U per frame" and it's not exceeding that?
I tested 10MHz and above and the only changed thing is "UUUU" frames on the output become faster.

**Comment by bastibl** [comment]
There was no science behind my tests. The flowgraph you linked produces a frame every 300ms. If the Us appear in about the same rate, it's probably OK. Also if a receiver is able to receive all sent frames, there were no underruns during the frame, since this would have corrupted the transmission. I'd assume these type of tests are good enough.

**Comment by YamanDaif** [comment]
I got it working now, the problem was a broken antenna on one of the ends. Thank you for your fast replies!  
I'm closing this issue!
