### ISSUE TITLE
Ping Rx from Tx

### ISSUE THREAD

**Issue by Alexis000000** [bastibl/gr-ieee802-11#312]
Hello Bastian,

I am using your code in a European project and I need to establish a connection with the Tx and Rx on two seperate machines.
Until now I was not able to do so and I do not understand the reason. I have attached the Tx code below.
![Tx_Code](https://user-images.githubusercontent.com/72496906/137165546-52b44fbd-f8ea-400b-8a80-58c670e3c741.png)
and the commands that I have used on the Tx host are the following
sudo ip tuntap add dev tap0 user ${USER} mode tap
sudo ifconfig tap0 down
sudo ifconfig tap0 hw ether 12:34:56:78:90:ab
sudo ifconfig tap0 mtu 440
sudo ifconfig tap0 up
sudo ifconfig tap0 192.168.200.1
sudo route del -net 192.168.200.0/24
sudo route add -net 192.168.200.0/24 mss 400 dev tap0
sudo tc qdisc del dev tap0 root
sudo tc qdisc add dev tap0 root netem delay 10ms

And on the Rx side, I entered the following commands:
sudo ip tuntap add dev tap0 user ${USER} mode tap
sudo ifconfig tap0 down
sudo ifconfig tap0 hw ether 30:14:4a:e6:46:e4
sudo ifconfig tap0 mtu 440
sudo ifconfig tap0 up
sudo ifconfig tap0 192.168.200.2
![Rx code](https://user-images.githubusercontent.com/72496906/137176430-82652f62-f34e-4869-a5b0-9ccb41dc51bf.png)

I am using 2 USRP b210 and they are connected via SMA cables with 30 dB attenuator.
When I try to ping the Rx host from Tx I get "host unreachable"
IPERF also doesn't work 
Can you help me out ?

Kindly

**Comment by bastibl** [comment]
My understanding is that on TX you don't use a Tun/Tap block. So this is not connected to the network stack, i.e., you cannot ping.

Also ping requires bi-directional communication, i.e., just running TX won't let you ping something.

But apart from all that: This is the most complex setup that also requires some knowledge in networking. Use the unmodified example flowgraphs and make sure that there is at least basic connectivity. Everything else can be figured out with Wireshark.
