### ISSUE TITLE
Receiving CSI from the code

### ISSUE THREAD

**Issue by iloveiclab** [bastibl/gr-ieee802-11#314]
Hi Bastia,

One way to log the CSI value in the previous discussion is by printing out "d_H[I]" in the ls.cc file. The modified code is as follows.

```
noise += std::pow(std::abs(d_H[i] - in[i]), 2);
signal += std::pow(std::abs(d_H[i] + in[i]), 2);
d_H[i] += in[i];
d_H[i] /= LONG[i] * gr_complex(2, 0);                               
cout << "CSI" << d_H[i] << endl;
}
d_snr = 10 * std::log10(signal / noise / 2);
```

I know that 'in' is subcarriers here, but I do not understand why d_H is CSI after some operations. Is it just the equations or a principle? Could you explain it to me? Thanks~

Furthermore, in base.cc file, there is the declaration of LONG, but I still don't know what the meaning of LONG is and why do we perform LONG[i] * gr_complex(2, 0) instead of gr_complex(2, 0) here.

Thank you,
James

**Comment by bastibl** [comment]
`LONG` is the long training sequence, i.e., what is sent. So `in[i] = LONG[i] * H[i]`. Where H[i] is the impact of the channel on subcarrier i.

**Comment by iloveiclab** [comment]
Oh, I got the reason of dividing by LONG.

But why do we calculate CSI by adding subcarrier (`d_H[i] += in[i]`) and dividing by 2 and `LONG` (`d_H[i] /= LONG[i] * gr_complex(2, 0)`)? Why don't we directly divide subcarrier by LONG, i.e., `in[i] / LONG[i]`, to obtain the channel?

Moreover, can we randomly change the content in `LONG`?

Thank you,
James

**Comment by bastibl** [comment]
Because the Long sequence is sent 2.5 times, so it uses two OFDM symbols for a better estimate.
You cannot just change Long.

**Comment by iloveiclab** [comment]
If I'd like to change LONG, I should change `LONG` and `(i == 32) || (i < 6) || (i > 58)` simultaneously, shouldn't I?

Besides, I find that the first few bits in LONG is 0. Is it for zero padding?

Thank you,
James

**Comment by bastibl** [comment]
Sorry, but you give zero information about your planned changes to LONG. It's not possible to help you. You cannot just change LONG arbitrarily.

**Comment by iloveiclab** [comment]
Oh, I got it. Thank you.
However, I want to ask about another problem. What is the unit of CSI amplitude value? Is it the dbm or others?
Thank you for your response in advance.

**Comment by bastibl** [comment]
SDRs are usually not calibrated. You'd need a table that maps the amplitude at a given bandwidth, gain, and sample rate to a power value. But usually you don't have this. AFAIK, UHD recently introduced something like this, but I didn't have a closer look.
