### ISSUE TITLE
BladeRF with Transceiver.grc 

### ISSUE THREAD

**Issue by YamanDaif** [bastibl/gr-ieee802-11#317]
Hi Bastian! 
I'm having trouble with getting the wifi_transceiver.grc work with bladeRF and I wonder if you have any advice I might use to make it work! 
I ready tested wifi_rx.grc by changing the source to gr-osmocom source and it seemed working. however, the Wireshark pcap file shows nothing (24 bytes) and I  don't know if it's a DC offset that I'm not aware of or if it's a Wireshark. 
the help to make it work would be much appreciated! 
This is a screenshot of the wifi_rx I'm using.

![248208808_309289554353552_6358664700195588764_n](https://user-images.githubusercontent.com/66362955/141467994-17e69280-709c-42a0-9ce8-a2e18ad05593.png)

**Comment by bastibl** [comment]
What are you trying to receive? There is no WLAN mode that uses 30MHz... You cannot just change parameters arbitrarily. Why don't you first try to receive WLAN frames from a normal WLAN card? Then, try replacing the transmitter with an SDR.

**Comment by YamanDaif** [comment]
I'm trying to receive its-g5 from Cohda box. 
the sample rate was 20M as it should be for the its-g5 but the results are the same and the .pcap is still empty. I thought that if I change the source/sink in the transceiver file it should work but it seems that this is not the case.

**Comment by bastibl** [comment]
ITS-G5 is based on 11p, which uses 10MHz channel, so you should probably set the sample rate to 10MHz.

**Comment by YamanDaif** [comment]
Hey!

After getting :
```
RuntimeError: gr::tuntap_pdu::make: tun_alloc failed (are you running as root?)
```
I disabled the the  Tuntap and Ethernet encapsulation and added a message strobe as seen in the screenshot below. It works fine for receiving but not for sending though. Can you find anything wrong in the flowgraph that might be the reason why bladeRF is not sending the message strobe? 
I'm sending its_g5 from BladeRF and receiving on HackRF.
![Screenshot_wifi_transceiver](https://user-images.githubusercontent.com/66362955/141786033-f6c48202-d039-40da-bbe7-6d0cdba9a2f4.png)

**Comment by bastibl** [comment]
The TUN/TAP interface requires setup as demonstrated in the apps/nic.sh script. There is also a dedicated TX flowgraph that you could try with the osmocom sink. But actually it looks good to me. Check if the other device can receive frames in the first place (e.g. from another Cohda), try different gains (I don't know the valid gain distributions of the BladeRF 2.), check antenna ports etc.

**Comment by YamanDaif** [comment]
It works fine now! it was an antenna port problem. Thank you for your fast support!

Yaman

**Comment by bastibl** [comment]
Thanks for the feedback. Happy it works.
