### ISSUE TITLE
HOW to get CSI

### ISSUE THREAD

**Issue by xushanzhizhang** [bastibl/gr-ieee802-11#319]
Hi Bastian,

I wanted to know if I can get Channel State Information from wifi_rx.
How to process the obtained file (. dat or. pcap) with MATLAB
I look forward to your reply！！

**Comment by bastibl** [comment]
The example flowgraph of recent versions show how CSI can be plotted. The same data can be piped into a file sink and read w/ Matlab. Its a binary file.

**Comment by xushanzhizhang** [comment]
I run wifi_ rx.grc(maint_3.7), but there is no response and output.

Is there anything you need to set and pay attention to

**Comment by bastibl** [comment]
It was not back-ported to 3.7. You have to update or back-port yourself.

**Comment by xushanzhizhang** [comment]
You mean I need maint_3.8 or higher to get CSI?

**Comment by bastibl** [comment]
yes.

**Comment by xushanzhizhang** [comment]
Thank you very much for your reply. I plan to install maint_3.8 to get CSI
