### ISSUE TITLE
Tag check removed on GR master

### ISSUE THREAD

**Issue by willcode** [bastibl/gr-ieee802-11#320]
There is no `tag_checker.h` on `master` in https://github.com/gnuradio/gnuradio/pull/4912
```
[  2%] Building CXX object lib/CMakeFiles/gnuradio-ieee802_11.dir/chunks_to_symbols_impl.cc.o
/<prefix>/grmaster/src/gr-ieee-80211/lib/chunks_to_symbols_impl.cc:20:10: fatal error: gnuradio/tag_checker.h: No such file or directory
   20 | #include <gnuradio/tag_checker.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by bastibl** [comment]
Thanks for letting me know. This turned out to be an used include :-) I just pushed a fix that removes it https://github.com/bastibl/gr-ieee802-11/commit/dec30cbed4e2f2fc3d068e71a927269b843e35b2
