### ISSUE TITLE
No reception/transmission with USRP X310

### ISSUE THREAD

**Issue by pierregalant** [bastibl/gr-ieee802-11#324]
Hello bastibl, sorry for disturbing you again. I am running gnuradio 3.7 with corresponding compatible versions of gr-foo and gr-ieee80211 installed on virtual machine and it works great.

Now, I am trying to receive beacons with your RX.grc. As equipment I have a USRP X310 that I have connected via ethernet. I have verified the USRP link and it works. However, when I run your RX.grc , the led blinks under RX1/TX1 antenna out but I do not receive any packet.

I am sending message strobe using your TX.grc with a hackrf and I receive the message strobe under wireshark with a internal Wi-Fi but I do not receive anything in the PCAP file generated by  the USRP running RX.grc even thought in the terminal, I have the message "long frame at 320"

I have verified the ip address and frequency but nothing seems to work.

Same for transmission. When I tried to transmit message strobe by replacing the osmocom block with the URSP UHD block, there is no transmissions. Can you please verify my parameters. 

![usrpx310](https://user-images.githubusercontent.com/77594215/143874293-1601a0ab-bceb-4719-82b0-8402146dfd3b.png)
![usrpx310-1](https://user-images.githubusercontent.com/77594215/143874299-3fbc6ec8-f2a7-42e5-9195-97879a9531ea.png)
![usrpx310-2](https://user-images.githubusercontent.com/77594215/143874303-6d43a4ca-fdd1-4fc7-9ede-3e62fcaabaf8.png)

**Comment by bastibl** [comment]
Try a different gain.
