### ISSUE TITLE
Run error (gr-ieee802-11-maint-3.8/examples/wifi_rx)

### ISSUE THREAD

**Issue by xushanzhizhang** [bastibl/gr-ieee802-11#325]
Hi,bastibl:
    I want to use USRP N210 to obtain CSI information, but the following error occurs. What should I do？
![捕获1](https://user-images.githubusercontent.com/81599145/144196220-a560742f-8252-41b0-8881-fdedc578d831.PNG)

**Comment by bastibl** [comment]
First of all, you should start with the unmodified flowgraph. It looks like you changed the clock sync mode. You can try changing it.
But this is an issue with your SDR that is unrelated to this module. As suggested, see the application notes of your SDR and in question contact the vendor, for example, through the USRP users mailing list.
