### ISSUE TITLE
wifi_phy_hier.grc Error!

### ISSUE THREAD

**Issue by SoulH-qqq** [bastibl/gr-ieee802-11#326]
Hi,
thank you for your amazing software. I have compiled gr-foo 3.8 and gr-802.11 3.8. My system is Ubuntu 18.04. My gnuradio version is as follows:
![Screenshot from 2021-12-16 09-38-09](https://user-images.githubusercontent.com/54933169/146346633-b1def068-bad6-4c9f-aaeb-51f401c9752e.png)
I also installed swig！But when I open wifi_phy_hier.grc, the following problems still occur!
![Screenshot from 2021-12-16 09-31-35](https://user-images.githubusercontent.com/54933169/146347080-ed9e2b17-3f75-4f3b-9b65-f3013309c963.png)
I don't know what to do, can you help me! !

Best,
Hao Sun

**Comment by bastibl** [comment]
Please see the readme. You have to set the block path and configure environment variables.

**Comment by SoulH-qqq** [comment]
I made the following changes according to the readme:
![Screenshot from 2021-12-17 03-04-31](https://user-images.githubusercontent.com/54933169/146482374-7fdf076d-392a-484d-8ad5-0df21224bbdf.png)
When I tried to open the /usr/local/share/gnuradio/grc/blocks directory, I found the following files:
![Screenshot from 2021-12-17 03-07-08](https://user-images.githubusercontent.com/54933169/146482562-475f3720-1940-472a-b194-bffb9f7c0b37.png)
Only files starting with “foo”. I found that these files are the same as those in the gr-foo-maint-3.8/grc directory. So I tried to copy the files in the /gr-ieee802-11-maint-3.8/grc directory to the /usr/local/share/gnuradio/grc/blocks/ directory, the results are as follows:
![Screenshot from 2021-12-17 03-13-41](https://user-images.githubusercontent.com/54933169/146483124-a668997e-569a-4619-a850-7238e0226a21.png)
But when I open wifi_phy_hier.grc the error is not resolved.
![Screenshot from 2021-12-17 03-17-31](https://user-images.githubusercontent.com/54933169/146483409-f65e2fcf-8ced-473b-984c-509d5b623e88.png)

**Comment by SoulH-qqq** [comment]
The ieee802.11 module can be searched in grc:
![Screenshot from 2021-12-17 06-50-50](https://user-images.githubusercontent.com/54933169/146501781-be0d9a3e-00b3-4b31-a358-84fd26da5731.png)

**Comment by bastibl** [comment]
You have to set the environment variables (PYTHONPATH, LD_LIBRARY_PATH) as described in the readme.

**Comment by SoulH-qqq** [comment]
Sorry, I did not see how to set the environment variable in the readme, can you tell me how to set it, or the location of the setting instructions.

**Comment by bastibl** [comment]
It's like this: https://www.wime-project.net/installation/#adapt-environment-variables but with the paths that you used. So don't just blindly copy paste. Also, this is the same for each OOT. So you can Google, check the GNU Radio wiki, etc.

**Comment by SoulH-qqq** [comment]
I have reconfigured the environment variables according to https://wiki.gnuradio.org/index.php/InstallingGR.
![Screenshot from 2021-12-20 07-52-36](https://user-images.githubusercontent.com/54933169/146731778-8b921623-603f-435a-8a9a-c39e91fd4ff0.png)
When I open the Python interaction, import 802_11 still fails. Opening wifi_phy_hier.grc is still the original error.

**Comment by bastibl** [comment]
So the obvious question: Is the module actually installed under `/usr/lib/python3/dist-packages`? Is the lib under `/usr/lib`. I guess not... That's what I meant with don't just blindly copy-paste commands....

**Comment by SoulH-qqq** [comment]
![Screenshot from 2021-12-20 07-59-37](https://user-images.githubusercontent.com/54933169/146732652-bee76b76-c0d7-43a4-a920-cb1fb1fe6af6.png)
This shows that gnuradio is installed in the /usr directory.
![Screenshot from 2021-12-20 08-01-41](https://user-images.githubusercontent.com/54933169/146732864-3ce15ff4-0f83-4bde-a2fe-aee4d49a67e4.png)
This indicates the location of the Python library.
So I set environment variables in the .bashrc file:
export PYTHONPATH=/usr/lib/python3/dist-packages
export LD_LIBRARY_PATH=/usr/lib

**Comment by bastibl** [comment]
GNU Radio already works. The question where you installed the OOT, i.e., this module. Please write to the GNU Radio mailing list, if you have any other question. I cannot provide this level of support at the moment.
