### ISSUE TITLE
Make Error 

### ISSUE THREAD

**Issue by asadaleee** [bastibl/gr-ieee802-11#329]
When I run make command at gr-foo, I get the following error. It's probably because of the changes in the code. If you could please tell me what changes in teh code shallI make to resolve the error. Thanks. 

/gr-ieee802-11/lib/chunks_to_symbols_impl.cc:27:38: error: could not convert 'gnuradio::get_initial_sptr(T*) [with T = gr::ieee802_11::chunks_to_symbols_impl]()' from '
![Error](https://user-images.githubusercontent.com/73308202/155536450-92dc34a1-c66c-452e-a811-8b6da794a2f4.png)
std::shared_ptr<gr::ieee802_11::chunks_to_symbols_impl>'
to 'gr::ieee802_11::chunks_to_symbols::sptr' {aka 'boost::shared_ptr<gr::ieee802_11::chunks_to_symbols>'}
   27 |     return gnuradio::get_initial_sptr(new chunks_to_symbols_impl());
      |            ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                                      |
      |                                      std::shared_ptr<gr::ieee802_11::chunks_to_symbols_impl>
make[2]: *** [lib/CMakeFiles/gnuradio-ieee802_11.dir/build.make:63: lib/CMakeFiles/gnuradio-ieee802_11.dir/chunks_to_symbols_impl.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:206: lib/CMakeFiles/gnuradio-ieee802_11.dir/all] Error 2

**Comment by bastibl** [comment]
Since you didn't give any information about your environment, I'd suggest to (1) make sure that there is only one version of GNU Radio on your PC without any left-overs from other attempts (2) install the version of this module that matches your installed version of GNU Radio.
