### ISSUE TITLE
Stuck in running examples/wifi_transceiver

### ISSUE THREAD

**Issue by gcc17** [bastibl/gr-ieee802-11#332]
Hi, the running of `examples/wifi_transceiver` is stuck in my testing. It keeps printing 'O' on the terminal. 
branch: maint-3.7
system: ubuntu 16.04
device: USRP B210

Screenshot for running `wifi_transceiver`:
![wifi_transceiver_stuck](https://user-images.githubusercontent.com/46296716/161894243-3ebe3de1-d06e-4086-a401-4d2dc427aefa.png)

The running of `examples/wifi_loopback` looks good:
![wifi_loopback_ok](https://user-images.githubusercontent.com/46296716/161894426-faa544d3-665c-4ca2-a489-508694e39114.png)

I cannot figure out where it is that the testing gets stuck. When running `wifi_transceiver`, the memory usage shown by `top` is less than 10%, so the memory should not be the bottleneck. I would appreciate it a lot if you can offer some advice for debugging.

**Comment by gcc17** [comment]
I repeated the same installation process on another computer, and the testing of `wifi_transceiver` worked well. 
![good_case](https://user-images.githubusercontent.com/46296716/161927135-26091f43-2033-45ee-89c2-06f93a676644.png)

Both computers are Ubuntu 16.04 and their GNU Radio versions are the same... Are there any other factors can cause the difference?

**Comment by bastibl** [comment]
Memory doesn't matter too much, it's the CPU that's important. If the CPU cannot keep up with the samples, you experience overruns, and streaming is restarted all the time. Also running `volk_profile` could make a difference. Make sure that it was run on the first PC.

**Comment by gcc17** [comment]
Thanks for your reply! I have runned `volk_profile` on both PCs. It seems that the generated files have a few differences. Do these differences matter? Actually the first PC has a newer processor than the second one, while the first one has 8 GB memory and the second has 16 GB. 
<img width="859" alt="volk_cmp" src="https://user-images.githubusercontent.com/46296716/163137412-0fe37463-24e3-44bd-9696-1d20ec9eb06c.png">

**Comment by bastibl** [comment]
Memory is not the problem. The fact that different implementations are preferable on different CPUs is exactly why you have to run `volk_profile`. So this is also as expected. One PC is just not fast enough, it seems.
