### ISSUE TITLE
What is 192.168.123.2 in ./nic.sh and your video?

### ISSUE THREAD

**Issue by asadaleee** [bastibl/gr-ieee802-11#334]
Dear Sir, 

In your following video, what is 192.168.123.2? I ran WiFi_transciever.grc and ./nic.sh. However, when I ping or ssh 192.168.123.2, I get the host unreachable. Do I need to have a separate USRP on another computer which will get the above IP address and then I will be able to ping it? 

https://www.youtube.com/watch?v=tAVgsJLM-sc

Let me take the opportunity to ask a couple of more questions. 

1. How do I achieve the following? How do I make USRP communicate with Normal WiFi Card? 
 "A USPR is communicating with a normal WiFi card."

2. What do you mean when you say, "put the card in monitor mode"?
Do you mean to start Wireshark capturing?

3. Normally in WiFi, we have an Access Point to which an STA gets connected to. I don't see AP in this project. We have transmitters and receivers everywhere. Am I missing something?  

I understand, I am disturbing you. However, your valuable time will give me a direction to pursue. I have been working on this project for the last one month. However, I am unable to make enough progress. 

Looking forward to hearing from you. 

Thanks.

**Comment by bastibl** [comment]
You seem to lack fundamental knowledge about IP, WLAN and networking in general. This is primary an issue tracker for bugs in the code. Your question is better suited for the GNU Radio mailing list or the GNU Radio matrix chat.
