### ISSUE TITLE
How to export I/Q data?

### ISSUE THREAD

**Issue by csy990406** [bastibl/gr-ieee802-11#336]
Thanks for your efforts on this great project.  I am using the phone as AP to send beacon frames and using usrp to receive the frames. How can I export the received I/Q signals to a txt file?

**Comment by bastibl** [comment]
You mean, just the samples that correspond to frames? This is at the moment not supported. You could extend the Frame Equalizer block to do this. But at this stage, the short preamble is already removed. So it depends on your exact application. CQI can be extracted out-of-the box, if this could be used instead.
