### ISSUE TITLE
Transmission power range of USRP N210

### ISSUE THREAD

**Issue by xushanzhizhang** [bastibl/gr-ieee802-11#338]
Hi,Bastibl:
    I'm bothering you
   When using USRP N210 to transmit signals, the transmission power can be changed by adjusting gain
What is the range of transmission power? What is the corresponding relationship with gain?

**Comment by bastibl** [comment]
This is a question for Ettus and not really related to this project. Anyways, you could have a look at their [knowledge base](https://kb.ettus.com/Knowledge_Base). In short, it depends on your daughter board.  You can check the gain range with `uhd_usrp_probe`. Usually, USRPs are not calibrated, i.e., you cannot easily map gain to output power. But AFAIK they introduced an API that might enable this (at least give an estimate of the output power). You have to check the wiki and API docs.

**Comment by xushanzhizhang** [comment]
Is this item applicable to USRP X310

I want to use&nbsp;USRP X310&nbsp;to receive WiFi signals

thanks





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bastibl/gr-ieee802-11"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月2日(星期一) 下午4:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bastibl/gr-ieee802-11] Transmission power range of USRP N210 (Issue #338)





 
Closed #338.

**Comment by bastibl** [comment]
Yes.
