### ISSUE TITLE
ImportError:/usr/local/lib/libgnuradio-foo.so.1.1.0git:undefined symbol

### ISSUE THREAD

**Issue by carolineChenCoder** [bastibl/gr-ieee802-11#340]
![image](https://user-images.githubusercontent.com/19708940/166975547-c49fa639-5f59-46b0-8d33-ff6f2f66dcec.png)
Hi, I meet this problem after I create my block include gr-foo.
I don't understand what's meaning.
Could you help me solve it?
Thank you so much!

**Comment by bastibl** [comment]
So you extended gr-foo, are actually using gr-ieee802-15-4, but open the issue for the gr-ieee802-11 repository :-) Anyway, the message_in function (i.e., you PMT handler) didn't end up in the library. Maybe you need to recompile or check for related errors (typos etc.)

**Comment by carolineChenCoder** [comment]
Hi, bastibl,

Thank you，I have solve that problems.
But I have another problem about the function 
 message_port_pub(pmt::pmt_t port_id, pmt::pmt_t msg)
This is the orignal function.
I see that mac.cc in gr-ieee802-15-4 have used this function by message_port_pub(pmt::mp("pdu out"),pmt::cons(pmt::PMT_NIL,pmt::make_blob(d_msg,d_msg_len))).
I use the same function like yours, it not worked and show errors without objective pmt::cons(pmt::PMT_NIL,pmt::make_blob(d_msg,d_msg_len).
Could you tell me how to solve this error?
Thank you!

**Comment by bastibl** [comment]
Sorry, but I have no idea what you're talking about. These are, however, just C++/GNU Radio problems. You could write to the GNU Radio mailing list or their Matrix chat. Also it might make sense share a link to the repo and the particular part of the code that you're talking about. Overall, it sounds like you are just not very experienced with C++.

**Comment by carolineChenCoder** [comment]
ok, thank you!
