### ISSUE TITLE
Is that possible to interfere with the long training sequence by sync with the short train sequence?

### ISSUE THREAD

**Issue by wenjinzhang** [bastibl/gr-ieee802-11#341]
@bastibl 

Hi,

Thank you for sharing the amazing project. It is helpful for me to understand the IEEE 802n. I'd like to ask whether we can apply the correlation method to the short training sequence of the OFDM structure to detect the existence of the short training sequence and replay a specific signal using another USRP immediately to interfere with the long training sequence.

For the detailed implementation of the transmitter, I also want to know where you add the short training symbols and long training symbols to the OFDM packet. I find the Long symbol array defined at 'base.cc' file but seem other functions never call it.

Thank you very much for your consideration!

**Comment by wenjinzhang** [comment]
Specifically, I need to know the clean short training sequence because I will calculate the correlation between the clean short training sequence and the received sequence.

**Comment by bastibl** [comment]
On TX side, the sync words are set (in frequency domain) in the OFDM Carrier Allocator. Generating the long training sequence is a bit tricky, given its unusual structure. See here: https://github.com/bastibl/gr-ieee802-11/blob/maint-3.8/utils/sync_words.py

**Comment by wenjinzhang** [comment]
Thank you very much and the sync_words.py make sense to me. If I understand correctly, you generate the sync words offline and copy them to OFDM Carrier Allocator.

**Comment by bastibl** [comment]
Yes, since they are fixed, they are just copied at the start of every frame.

**Comment by wenjinzhang** [comment]
I got it. Thank you very much.
