### ISSUE TITLE
a problem about crc32

### ISSUE THREAD

**Issue by ggcam** [bastibl/gr-ieee802-11#342]
Hi！
  In the file named “decode_mac.cc”， is there something meaningful about the code:"if(result.checksum()!=558161692")?Why is the checksum number always 558161692?When i change my payload message,i find that the checksum number is always 558161692!Please tell me the reason.It's my pleasure to take your advice.
                                                                                                                                                                                             Thanks

**Comment by bastibl** [comment]
The transmitter calculates and sets the CRC so that this is the case. If you wouldn't know the CRC in advance, there would be no way to check it.
Another way to implement it, might be to calculate the CRC leaving out the last 4 bytes and comparing the results to the last 4 bytes.
