### ISSUE TITLE
About CSMA

### ISSUE THREAD

**Issue by Leoplt** [bastibl/gr-ieee802-11#343]
Hi,bastibl:
    I use "wifi_tx" to send WiFi data (as follows, unmodified)
    Is the sender sending WiFi packets all the time without CSMA?
<img width="278" alt="捕获1" src="https://user-images.githubusercontent.com/88756718/170805037-252ba149-8518-46ac-9063-24d3618be235.PNG">

**Comment by bastibl** [comment]
There's no CSMA. It just send the frame. It's impossible meet the timings of the CSMA procedure on a PC.
