### ISSUE TITLE
Just a general question about the blocks

### ISSUE THREAD

**Issue by jackdvd** [bastibl/gr-ieee802-11#349]
First of all thanks for sharing this. 
Sorry, if this sounds like a stupid Q as I am new to SDR. Why is the block diagram so complicated and doesn't use any direct filter like LPF etc? Is this because the encoding of the WiFi itself is complicated? Is there any document explaining the role of each blocks?
Is there a simple way to achieve this like using blocks like LPF, GFSK demod etc.?

**Comment by bastibl** [comment]
There is no simple way to implement a WLAN receiver with just some basic components. Yet, for example, the moving average blocks are a LPF. Or the Sync Long block uses a cross-correlation FIR filter internally. So these components might be in there somewhere, but there's some more complexity to it that requires dedicated/specialized blocks.

**Comment by jackdvd** [comment]
Thanks for the response. Could you please recommend some resource for understanding the internals of WiFi signals. Tried to google it but not coming across any good ones.

**Comment by bastibl** [comment]
I just used the standard when implementing the transceiver. And if I didn't get something, I searched for information on this specific topic. I also don't know a tutorial or introductory material. An earlier version of this transceiver is also discussed in my thesis: https://www.bastibl.net/bib/bloessl2018physical/
