### ISSUE TITLE
Can't send packet but can receive packet

### ISSUE THREAD

**Issue by rom1tes** [bastibl/gr-ieee802-11#350]
Hello,

I've been using your project to sniff some V2X messages (Based on 802.11p standard). The reception works well. The next step is to send some messages back, but I can figure out why it does not work. It does not seems to encode correctly. 
For instance this is what I receive (with a bladeRF) from the working device :
![wifi_rx](https://user-images.githubusercontent.com/101864821/177574154-70a44d46-a0d3-40c9-9d97-f61381587f06.png)
As you can see, the reception works fine and I can save the messages that are sent. 
On the other hand, This is what I receive (with a bladeRF) when I send something with (another bladeRF) :
![wifi_tx](https://user-images.githubusercontent.com/101864821/177574654-dcb2e511-0893-46d8-aad9-ccb7d89f732d.png)
I have tried to do volk_profile but I get the same result. As you said in another issue, It might be related to the CPU, with the wifi_tx on, my CPU is not overload at all (5% in total) so is there a way to boost the CPU consumption ?
I have the same problem on 2 computer with different installation.

Thank you very much.

**Comment by bastibl** [comment]
The auto-correlation is constantly high, which triggers frame detection all the time. This causes load and makes missing frames much more likely. You can try to increase the distance. Shield the transmitter. Or check if there are some dc offset correction settings for the BladeRF.

**Comment by liiso7** [comment]
@rom1tes Hello, how do you use bladeRF to sniff messages? Have you tried any other frequencies? Can you provide me with your.GRC flow chart? Thank you very much!
