### ISSUE TITLE
Rate of CSI reception

### ISSUE THREAD

**Issue by lrisd** [bastibl/gr-ieee802-11#351]
hello bastibl:
I successfully collected CSI data using gnuradio3.8.
I want to know the approximate rate of CSI data collection is what KHz? What are the main factors that affect it?

**Comment by bastibl** [comment]
CSI is estimated for every received frame.

**Comment by xushanzhizhang** [comment]
Thank you for your reply！
How much Hz is the frame receiving rate, and what factors affect it？

**Comment by lrisd** [comment]
Thank you for your reply！
How much Hz is the frame receiving rate, and what factors affect it？

**Comment by bastibl** [comment]
In the loopback example, there is an interval parameter that can be lowered to increase the frame rate. In a normal scenario it depends on the transmitter.
