### ISSUE TITLE
Beacon Frame is not detected

### ISSUE THREAD

**Issue by thayheng** [bastibl/gr-ieee802-11#355]
Hello Sir,

Thank you for your work it is very helpful for me. Although, I have one problem. I have a recorded complex float (fc32) file of WiFi beacon and I loaded it with **FILE SOURCE** using your wifi_rx.grc but when I monitor the detected frame on wireshark, it does not detected it as a beacon frame but as dataframe instead. Please help and see my set up below.

Setup:
Bare-metal machine
Intel i7, 16Gb RAM
Ubuntu 20.04
GnuRadio 3.8.2.0
no SDR Device (Recorded File Source)
![image](https://user-images.githubusercontent.com/24226606/185093831-34b689c9-945a-4da0-a023-33df010e77b9.png)

Here is what I detected

![image](https://user-images.githubusercontent.com/24226606/185095286-9043f7a3-d7c2-48ab-9a8c-5c5383302466.png)

I believe the detected frame should be a beacon management frame and not data frame.

**Comment by bastibl** [comment]
This module just decodes bits; it does not interpret them. Parsing is done in Wireshark, and Wireshark thinks it is a data frame. I never had any issues with Wireshark parsing WLAN, so I would assume this is a data frame. Just try a different AP, receiving and parsing beacon frames should work without problems.
