### ISSUE TITLE
Value cannot be evaluated or defined

### ISSUE THREAD

**Issue by JeanPaulBadjo** [bastibl/gr-ieee802-11#359]
I'm having the errors below when trying to run wifi_phy_hier:

![Screenshot from 2022-09-02 14-04-53](https://user-images.githubusercontent.com/38262490/188218169-1f1965f7-988b-4edc-a798-8088f6a93323.png)
![Screenshot from 2022-09-02 14-07-03](https://user-images.githubusercontent.com/38262490/188218208-0047b20d-567a-4df5-99f6-e3f3f1acb672.png)

I did some googling and I saw a number of responses from running the code through some IDE to see if its picking up the SO, to making sure the blocks and Library's are all communicating but it hasnt worked, and I'm worried that I might be typing in the commands wrong.  Below is the locations to the SO file, the blocks, and the libraries. 

![Screenshot from 2022-09-02 14-06-32](https://user-images.githubusercontent.com/38262490/188218187-a81ba426-3ff9-4bac-901b-92cd9a7801e2.png)

Please help me

**Comment by bastibl** [comment]
This is an installation issue. However, the information and the screenshots to not help much debugging this. Please see the readme and make sure that the various paths are set correctly.

**Comment by JeanPaulBadjo** [comment]
Ok, I ran into the same problem, however i went to version 3.10 and it worked perfectly. I have a few other questions but I'll open a new question.
