### ISSUE TITLE
wifi_loopback.grc issue

### ISSUE THREAD

**Issue by avinashkalyanaraman** [bastibl/gr-ieee802-11#36]
Hi,

I am trying to run wifi_loopback.grc. However, I notice nothing on the command line about the transmitted message and the plot is blank. Following is the output : 

Using Volk machine: sse4_a_64_orc
OFDM MAPPER: encoding: 0
set_min_output_buffer on block 31 to 96000
set_min_output_buffer on block 33 to 96000
set_min_output_buffer on block 35 to 96000
set_min_output_buffer on block 36 to 96000
set_min_output_buffer on block 39 to 96000
set_min_output_buffer on block 50 to 96000

<Blank after this>

The scope plot looks blank like this:

![image](https://cloud.githubusercontent.com/assets/1245911/16089605/ed740caa-32f9-11e6-9b17-5cb608bc98f1.png)

I am in the master branch, and wifi_phy_hier was built before executing the loopback.

Please let me know what might be the issue, and how I might be able to fix this.

**Comment by bastibl** [comment]
Really strange. I've never seen this.

Could you please start the flow graph from the command line by executing the generated python script (it's in the examples folder). GRC might hide some errors.

**Comment by avinashkalyanaraman** [comment]
Sure - here is the output of the generated python script. Looks identical as before. 

![screenshot from 2016-06-16 05 23 21](https://cloud.githubusercontent.com/assets/1245911/16090257/ce8434a8-3382-11e6-846e-afbc15596db7.png)

**Comment by bastibl** [comment]
You could try to enable debug / log output of blocks to try to find out where stuff breaks. 
Maybe also a git reset --hard and rebuild the flow graphs to assert that nothing was changed from the version in the repo.
Any chances that gr-foo is not compiled against the same version of GNU Radio?

**Comment by avinashkalyanaraman** [comment]
Thanks - I will try that and let you know how it goes.

The gr-foo is compiled against the same GR version.

I installed GnuRadio via apt-get as opposed to PyBombs. Any chance that could be an issue here?

**Comment by bastibl** [comment]
yes, that version is most likely horribly outdated.

**Comment by avinashkalyanaraman** [comment]
Version changing fixed it.
