### ISSUE TITLE
Trying to get a full understanding of what's happening

### ISSUE THREAD

**Issue by JeanPaulBadjo** [bastibl/gr-ieee802-11#360]
Hello again, 

This questions is mainly to get a better understanding of what's happening. As part of my project, I'm trying to broadcast in 802.11 to see if a device can see it (like my phone). Normally I know the broadcast MAC is FFFFFFFFFFFF but no matter how I type it in, the system is telling me that the value cannot be evaluated. 

![Screenshot from 2022-09-08 09-30-42](https://user-images.githubusercontent.com/38262490/189155376-5c3dcfe5-6a0e-428d-99d9-e0903abac149.png)

Am I modifying it incorrectly or is there a way to modify it so I can see the broadcast from any device?

Also I don't fully understand what the message strobe is doing. Is it like the classic "hello world" example from coding? Sorry if these questions are too basic. I am new to this but will continue to look for guides.  

![Screenshot from 2022-09-08 09-34-07](https://user-images.githubusercontent.com/38262490/189156879-8c739eb6-8f05-4894-a35c-eb7dd5f73cb6.png)

**Comment by bastibl** [comment]
Not sure what you are expecting to see on your phone. I'd start with setting the sample rate to 20M, select a channel, and try to receive the packets with your laptop, listening in monitor mode. When your card is in monitor mode, you can just send any frames and they will show up in Wireshark, for example. You won't see the SDR as an access point on your phone, because you're not sending a WLAN beacons. To do this, you would have to couple the transmitter with scapy as described in this talk: https://archive.fosdem.org/2019/schedule/event/gr_scapy/

**Comment by JeanPaulBadjo** [comment]
Hello again, 

I did some more digging and I think what you did here might be a way of doing what I am trying to do: **https://www.bastibl.net/gnuradio-wlan-scapy/**

I'm essentially just trying to make a beacon packet on my computer and broadcast it using an SDR and having a receiver that I already made "Sniff" it. 

In the link, how did you manage to type python code directly into GNUradio. If I could Directly type in the MAC Address I believe that would solve my problem.

**Comment by bastibl** [comment]
This is a separate external script that pushes the frames via UDP into the flowgraph, where they are received by the Socket PDU block.

**Comment by JeanPaulBadjo** [comment]
Ok. In the link I provided you were able to broadcast to "ff:ff:ff:ff:ff:ff". Is there a way to do this directly in the gnuradio transmitter you made? Or is making an external script that pushes frames the only way?

**Comment by bastibl** [comment]
That's what the example you posted is doing. You can configure MAC addresses in the WiFi MAC block. You only need Scapy if you want to assemble more complex frames (like beacons).

**Comment by JeanPaulBadjo** [comment]
Ok, Sorry for such basic questions. I'm guessing I'm just not inputting it correctly. So what would the general MAC address destination be to make it be seen by any wifi device? I've tried putting in the ff:ff sequence, the 0xff, 0xff sequence, etc.

No matter what I put in I keep getting an error like this. How would you input it?

**Comment by JeanPaulBadjo** [comment]
The image from my last comment didn't go through. Here is the error I receive.

![Screenshot from 2022-09-27 10-44-05](https://user-images.githubusercontent.com/38262490/192564404-aa02f52d-0ef4-4ce9-baee-48f2f3e550c2.png)

**Comment by bastibl** [comment]
`[0xff, 0xff, ...]`, like in the other fields.
