### ISSUE TITLE
HackRF One

### ISSUE THREAD

**Issue by pococ31** [bastibl/gr-ieee802-11#365]
I replaced the UHD Source with _"Soapy HackRF Source"_  and run the code in GNU radio companion version 3.10 but I am constantly getting "s00ss00ss00ss00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s" and the wireshark can't able to form any pcap from /tmp/wifi.pcap.

how to fix this issue ?

**Comment by bastibl** [comment]
The HackRF has an uncompensated DC offset, which continuously triggers frame detection. This was discussed in many issues.

**Comment by pococ31** [comment]
Thank you bastibl. Can you share the link of the discussed issues/suggestions that I could follow up.

**Comment by bastibl** [comment]
https://github.com/bastibl/gr-ieee802-11/search?q=hackrf&type=issues
