### ISSUE TITLE
Can't see transmitted signal

### ISSUE THREAD

**Issue by JeanPaulBadjo** [bastibl/gr-ieee802-11#366]
I'm using GNU radio to transmit beacon packets through wifi to a sniffing receiver. The receiver works well. I can see it every wifi signal through the sniffer. However I cannot see anything from my transmitter. I hooked it up to a spectrometer and it did indeed confirm that a signal was being transmitted but for some reason I cant see it.

The MAC address signal I am sending it to is ff:ff:ff:ff:ff:ff which is the general broadcast address so my phone should also be able to see it. But nothing. I also believe that I am in the correct frequency range. Any tips?

Below are images of the GUI and how I wrote the address. Should I input anything differently? I believe it should translate to ff:ff:ff:ff:ff:ff.

![Screenshot from 2022-10-12 13-09-53](https://user-images.githubusercontent.com/38262490/199485352-eb231743-402d-416c-809a-ec10d9f7604b.png)
![Screenshot from 2022-10-12 13-10-00](https://user-images.githubusercontent.com/38262490/199485354-3e2883c9-da35-45f0-b7c8-5810cfbcdc22.png)
![Screenshot from 2022-10-12 13-46-52](https://user-images.githubusercontent.com/38262490/199485356-dd8389e4-2b46-41d6-8bd7-d892fb00652a.png)

**Comment by bastibl** [comment]
If you try to receive this with a normal WLAN card, you will have to set a bandwidth/sample rate of 20MHz. Also I would increase the Pad Front. And try various gain settings.
