### ISSUE TITLE
Section Explaination

### ISSUE THREAD

**Issue by thayheng** [bastibl/gr-ieee802-11#370]
Dear Sir,
I am quite new on DSP as well as gnu radio and, I am hoping you could help with some explanation of this part of gr_wifi_receiver. I am not sure if these part include 3 main things as 1. de-noising 2. time-recovery (clock sync) 3. channel equalization (multi-path effect). If so, where does these processes take place in the receiver?

![image](https://user-images.githubusercontent.com/24226606/228192921-de566909-da91-481d-a00e-751616378f65.png)

**Comment by bastibl** [comment]
Not sure what exactly you mean with de-noising, but
- the frequency offset if estimated and compensated in sync long and sync short
- the time alignment of the frame is estimated in sync long (and cyclic prefix is removed)
- multi-path effects are compensated in the frame equalizer

**Comment by thayheng** [comment]
Thank you sir for your response! For de-noising, I refer to filtering process for should there be any noise in the signal.

**Comment by bastibl** [comment]
We don't do de-noising. I'm not sure what you had in mind specifically. But since the signal is not oversampled, there is no channel filtering or something like that.

**Comment by thayheng** [comment]
Ah, I see. Thank you sir.
