### ISSUE TITLE
ieee802_11 missing blocks moving average in maint-3.8

### ISSUE THREAD

**Issue by shen-tianji-gn** [bastibl/gr-ieee802-11#372]
I am using this module and facing the same issue with [#323](https://github.com/bastibl/gr-ieee802-11/issues/323). Here is additional information about this issue. Perhaps you could check the source file in the `maint-3.7` branch, as well as in the other branches within the `./grc` folder.

In the `maint-3.7` branch, the file [ieee802_11_moving_average_xx.xml](https://github.com/bastibl/gr-ieee802-11/blob/maint-3.7/grc/ieee802_11_moving_average_xx.xml) exists, but the corresponding `.block.yml` file is not present in other branches. Does this trigger the issue?

I will try it in GNU 3.7 later to see if it is the cause of the issue.

**Comment by slayerwalt** [comment]
I am using `GNU3.10` and `maint-3.10` branch, and I have same problem after installing `gr-foo` and `gr-ieee802-11`

![image](https://user-images.githubusercontent.com/77372975/231074696-525a6c13-2506-40cb-9f42-6e4cd2cea29a.png)

This block has different parameters with the 'Moving Average' block in Level Controllers which is shown below

![image](https://user-images.githubusercontent.com/77372975/231075408-adebfda8-98e7-4909-af36-ff0cb545d1c7.png)

I wonder whether could I just substitute this missing block with default one?

**Comment by shen-tianji-gn** [comment]
> I am using `GNU3.10` and `maint-3.10` branch, and I have same problem after installing `gr-foo` and `gr-ieee802-11`
> 
> ![image](https://user-images.githubusercontent.com/77372975/231074696-525a6c13-2506-40cb-9f42-6e4cd2cea29a.png)
> 
> This block has different parameters with the 'Moving Average' block in Level Controllers which is shown below
> 
> ![image](https://user-images.githubusercontent.com/77372975/231075408-adebfda8-98e7-4909-af36-ff0cb545d1c7.png)
> 
> I wonder whether could I just substitute this missing block with default one?

I think the right block you gave is in the `core` category of GNURadio, not in this module.

**Comment by slayerwalt** [comment]
> I think the right block you gave is in the core category of GNURadio, not in this module.

Yes, I find it in `Core/Level Controllers/Moving Average`

**Comment by slayerwalt** [comment]
@shen-tianji-gn I find that you should run `/examples/wifi_phy_hier.grc` first, then the 'missing blocks' problem will be fixed

**Comment by shen-tianji-gn** [comment]
@slayerwalt In my case, no.
It generates the `wifi_phy_hier.py.block.yml` file. And a new block `WiFi PHY Hier` is appeared. 
The block with key `ieee802_11_moving_average_xx` is still missing.

**Comment by bastibl** [comment]
You seem to be using the v3.7 version of the GRC files with a v3.10 installation. That won't work.
You might also have an older version of the PHY installed. So please open the 3.10 version of the PHY, build it, and re-open GRC.

**Comment by shen-tianji-gn** [comment]
> 

I am using GNURadio 3.8 with maint-3.8, and the `gr-foo` module is also on `maint-3.8`.

I tried to install the `maint-3.7` module on GNURadio 3.8, but it failed with an error during `cmake ..` .

But it works by using the same blocks `moving average` in `Core/Level Controllers/Moving Average` as @slayerwalt mentioned. I will close this issue.
