### ISSUE TITLE
Does the code support  802.11b 

### ISSUE THREAD

**Issue by commthu** [bastibl/gr-ieee802-11#373]
I open wifi_rx.grc,  I found there is FFT size of  64,  I think it is OFDM demodulation. I think it is 802.11g demodulation flowchart.  But 802.11b does not use OFDM. I doubt this code support 802.11b.

![image](https://user-images.githubusercontent.com/7654811/232274423-9d690eea-43e3-4320-871d-54d48d5247c2.png)

**Comment by bastibl** [comment]
This project mentions at multiple places that this is an IEEE 802.11a/g/p transceiver. It does not support 11b and, AFAIS, never claimed it would.
