### ISSUE TITLE
beacon transmit

### ISSUE THREAD

**Issue by Windy-with-sky** [bastibl/gr-ieee802-11#374]
hello! well, I've been studying your gr-ieee802.11 project lately and konw use Scapy to broadcast forged beacon frames for a fake Wireless Access Point. So I want to konw whether we can send the beacon frame, then the other usrp connects to the AP and communicates with it?Or make the usrp receive wifi so that the PC can connect the network

**Comment by bastibl** [comment]
This is not possible. See, for example, https://github.com/bastibl/gr-ieee802-11/issues/301 or https://github.com/bastibl/gr-ieee802-11/issues/313
