### ISSUE TITLE
Muitlple Receivers WiFi Card setup

### ISSUE THREAD

**Issue by Acoustical** [bastibl/gr-ieee802-11#378]
Hi there! I've follow your tutorial to setup WiFi Cards. I wonder if it is possible to setup WiFi Cards to do synchronization for multiple receivers. ( The WiFi MAC Block only have 1 src and 1 dst mac address )
![image](https://github.com/bastibl/gr-ieee802-11/assets/23265557/5eda4e2d-76c2-4ac3-b254-b2d2b5229c40)

Thank you so much!

**Comment by bastibl** [comment]
I'm not sure what you are asking for. The MAC addresses that is configured in this block just adds a static header to all frames that are transmitted. There  is no actual MAC functionality (like CSMA/CA or signaling w/ control and management frames).

**Comment by Acoustical** [comment]
Got it! Thanks for the reply! 

Forgive my previous unclear statement. I meant multiple receivers.

I've already found the answer to my question in closed issues ( [https://github.com/bastibl/gr-ieee802-11/issues/337](https://github.com/bastibl/gr-ieee802-11/issues/337) ).

Thank you again for the help!
