### ISSUE TITLE
Performance question & state of SDR wifi

### ISSUE THREAD

**Issue by roycamp** [bastibl/gr-ieee802-11#38]
I'm interested in this project and was wondering what the practicality of it is for a production deployment in the future.  

Do you have any insight into the performance of SDR wifi vs an off the shelf router? 

For OTA, are you able to achieve 802.11g speeds that are on par with common routers? 

For hardware, I assume the hardware running SDR wifi would need significantly higher specs.  Any insight into what those look like or are we still too early in the development of this technology?

How far out is 802.11n/ac? Are there major new challenges in expanding to those or is it merely an issue of time and materials.  

Thanks!

**Comment by bastibl** [comment]
This is mainly a physical layer implementation that is fully compatible with WiFi cards. It doesn't support full MAC layer functionality like sending ACKs in time. It is well known that is generally not possible with this architecture.
Standard compliant channel access for broadcast  transmissions is possible though. See here for example:
http://www.ccs-labs.org/bib/bloessl2014timings/
Implementing 11n and 11ac is an issue of bandwidth. At some point it will be too many samples to process them on a normal PC. At least for 11ac you would have to use an FPGA implementation.
