### ISSUE TITLE
wifi_tansceiver

### ISSUE THREAD

**Issue by mbalalzade** [bastibl/gr-ieee802-11#382]
hello, i want to use this repos. with balderf and an access point to connect to each other , and i know my access point MAC
now my question is in block of MAC_hier:
source MAC is the mac address of my bladerf?
and dest MAC is the mac address of my access point ?
and i dont know what is BSS?

**Comment by bastibl** [comment]
This won't work. Please search this issues, it was answered many times. 
https://github.com/bastibl/gr-ieee802-11/issues/374
https://github.com/bastibl/gr-ieee802-11/issues/301
https://github.com/bastibl/gr-ieee802-11/issues/313
