### ISSUE TITLE
radiotap_header

### ISSUE THREAD

**Issue by mbalalzade** [bastibl/gr-ieee802-11#388]
hello. I used this rep. with bladeRF and capture packets in wireshark . I want to know in a frame like CTS the part of radiotap: i recived signal with  30dbm power. now my questions are:
1- antenna signal refer to transmitted power or received power at my bladeRF antenna?
2- if it is received power at my bladeRF antenna why is 30dbm so where is the pathloss?

**Comment by bastibl** [comment]
The receiver cannot know absolute power levels. It just estimates the SNR based on the long training sequence and sets noise and power values of the radiotap header, such that the SNR corresponds to the estimated SNR: https://github.com/bastibl/gr-foo/blob/maint-3.9/lib/wireshark_connector_impl.cc#L102-L111
