### ISSUE TITLE
Overflow when using HackRF on wifi_rx.grc

### ISSUE THREAD

**Issue by CodeDragon82** [bastibl/gr-ieee802-11#391]
Overflow when using HackRF source on wifi_rx.grc:
<img width="196" alt="image" src="https://github.com/bastibl/gr-ieee802-11/assets/65504498/885e84a6-edb7-4a70-90f2-c83f252f6e1c">

(Same problem with both Soapy HackRF Source and osmocom Source.)

The only thing I've changed in the source input:
<img width="519" alt="image" src="https://github.com/bastibl/gr-ieee802-11/assets/65504498/5c446e19-11e9-4778-bb7d-05ee1309a834">

Also, I've compared my chart to the one in this issue but I still have the problem:
https://github.com/bastibl/gr-ieee802-11/issues/248

Extra info:
 - I have tested on a local Ubuntu system, WSL (window's subsystem), and a Kali Linux virtual machine, all with the same result.
 - Using the maint-3.10 branch:
   - The maint-3.8 branch doesn't install because there's missing a header file.
 - Installed:
   - gr-foo
   - gr-ieee802-11
   - gr-osmocom
   - hackrf (via apt)
   - libhackrf-dev (via apt)

(Please let me know if I'm missing any information that will be helpful.)

**Comment by razgino11** [comment]
I have encountered the same issue exactly, will update here if i figure it out, keep me updated if you do as well :)

**Comment by bastibl** [comment]
The HackRF has an uncompensated DC offset, which constantly triggers frame detection, overloading your PC. This was answered several times. Please search for HackRF in the Issues. In short, you somehow have to remove the DC spike through a rather sharp filter. Or 3rd party DC blocker blocks. Maybe the osmocom blocks can also do it.

**Comment by razgino11** [comment]
@bastibl Thank you! I did look before as well but your explanation helped clear things up,

I came across this amazing article:
https://www.rtl-sdr.com/wp-content/uploads/2017/02/Getting-rid-of-that-center-frequency-spike-in-gnuradio.pdf

which recommended this oot block for fixing the problem automaticly:
https://github.com/ghostop14/gr-correctiq/tree/master

seems to work great fixing the overflow, still havent figured everything out as far as making the example work but the overflows are gone for me on my hackrf :)

**Comment by bastibl** [comment]
For normal WLAN, you have to set the bandwidth/sample rate to 20MHz and make sure the signal you are trying to receive is actual 11a/g.

And you have to make sure that you only filter the DC spike but don't disturb adjacent subcarriers. I don't know this block, and was just wondering if you might have filtered out too much :-) There are also links to an adapted flowgraph for the HackRF. IIRC, this used an FFT filter that worked but was not optimized (so maybe it was more narrow than necessary, i.e., might have used more CPU than was actually required).

**Comment by razgino11** [comment]
@bastibl Thank you very much! setting it to 20 MHz and selecting the correct frequencies worked for me and im getting packets now using hackrf :)

**Comment by CodeDragon82** [comment]
@bastibl Thank you! I removed the DC spike and I'm getting WiFi frame in Wireshark. I've encountered another problem though. The algorithm seems to only pick up on short frames such as ACKs, CTSs and deauths, and not long frames such as data frames and beacons. Any idea on why this might be? 

Info:
 - Sampling at 20MHz.
 - Using the osmocom source into the DC spike module (correctiq).
 - Testing on channel 1, 2.4GHz.

**Comment by razgino11** [comment]
@CodeDragon82 
Checked on my setup and i have the same issue like you again, hadn't noticed i was only getting those packets before 
My setup:

- Sampling at 20MHz
- 802.11g on channel 7
- using the soapy hackrf source

**Comment by Cobi-Coder** [comment]
![Image](https://github.com/user-attachments/assets/53c2f952-ead8-4d81-acc9-1fd320a762cf)
I used the CorrectIQ block, but the 'O' overflow still occurs. What should I do?

**Comment by bastibl** [comment]
Either your PC is just not fast enough and cannot process the samples in real-time. Or the DC offset compensation is not good enough and it still triggers frame detection the whole time. One option is to run htop (with thread names) to get an idea whats going on. Or you use a tag debug after the sync short block to check if frame detection is triggered permanently.

**Comment by Cobi-Coder** [comment]
![Image](https://github.com/user-attachments/assets/df23e324-0332-447f-9f12-7592643ec33d)

![Image](https://github.com/user-attachments/assets/d342da96-1665-488a-a8e9-bf0ed0c720b1)

sorry for bothering, i used the debug tag block but still got 'O' overflow. This is the laptop i am using, do you think it is too weak to run?

**Comment by Cobi-Coder** [comment]
Asus TUF FA507 ( R7 7435HS / Ram 8 / SSD 512 / RTX 4060 / Màn 15,6 inch FHD 144hz 100% sRGB )
May be I will buy this, do you think it will work?

**Comment by bastibl** [comment]
In case you run this as a VM, try it natively. An i7 should be good enough.

It seems you are missing some basics. Maybe you should start with some of the examples and tutorials that GNU Radio provides: https://wiki.gnuradio.org/index.php/Tutorials
