### ISSUE TITLE
Tx is router，Rx is USRP

### ISSUE THREAD

**Issue by sarielkk** [bastibl/gr-ieee802-11#395]
Hello！ First of all, thank you for your work, it has been a great help to us. 

Is it feasible to use a router as Tx and USRP X310 as Rx to receive the wifi signal sent by the router? 
If it is feasible, can I just use the wifi_rx.grc file in the example to achieve it?

Looking forward to your answer.

**Comment by bastibl** [comment]
Yes, that's possible. But make sure to use 20MHz at theX310 and that the router sends 11g or 11a signals.

**Comment by sarielkk** [comment]
Thank you for your answer. 
By setting as you said, can we ensure WiFi signal received by USRP only comes from the router?

> Yes, that's possible. But make sure to use 20MHz at theX310 and that the router sends 11g or 11a signals.

**Comment by bastibl** [comment]
If you don't conduct the experiments in a faraday cage, there is no guarantee that the devices doesn't pick up other frames. They would have to be filtered out afterwards, if needed.

**Comment by sarielkk** [comment]
> 如果您不在法拉第笼中进行实验，则无法保证设备不会拾取其他帧。如果需要的话，之后必须将它们过滤掉。

Thanks for your reply, I will try as you said.

**Comment by sarielkk** [comment]
> If you don't conduct the experiments in a faraday cage, there is no guarantee that the devices doesn't pick up other frames. They would have to be filtered out afterwards, if needed.

Thanks for your reply, I will try as you said.
