### ISSUE TITLE
Need help in generating wifi Becons using HackRF (wifi_tx.grc)

### ISSUE THREAD

**Issue by ShivaAlethea** [bastibl/gr-ieee802-11#400]
Hi, Im new to this GNU Radio.
Can anyone please help me to create .grc for **Beacon** geneartion (using HackRF One).
I tried to ran [wifi_tx.grc](https://github.com/bastibl/gr-ieee802-11/blob/maint-3.10/examples/wifi_tx.grc), It is working.
But it is not generating any Beacons.

Also tried to follow https://user-images.githubusercontent.com/77594215/106764041-59bd3400-662f-11eb-8a87-994884fa0361.png

But im not able to get the values that i need to pass on **header_formatter**, **Packet_Header**, **OFDM_carrier_Allocator** and **FFT**.
![Screenshot from 2024-01-22 17-11-40](https://github.com/bastibl/gr-ieee802-11/assets/157352391/010d38a5-a8b5-4d20-bff1-136e60ceb5c2)

Can anyone help me to create this/new **.grc** for beacon generation.

Thank you

**Comment by bastibl** [comment]
From the screenshot I only see that something is red, so something goes wrong. the error is not on the screenshot, so I can only guess:
- make sure you use the correct version/branch of this module as indicated in the readme
- check cmake output, if something is missing and, therefore, stuff is not built
- make sure the paths are correctly set up as indicated in the readme

See this [blog post](https://www.bastibl.net/gnuradio-wlan-scapy/) and this [talk and slides](https://archive.fosdem.org/2019/schedule/event/gr_scapy/) for how to inject frames.

**Comment by ShivaAlethea** [comment]
Hi @bastibl Thank you very much for the reply.
With the help of above [blog post](https://www.bastibl.net/gnuradio-wlan-scapy/) created **beaconFrameGeneration.py** and **wifi_beacon_tx.grc**
**[wifi_tx.zip](https://github.com/bastibl/gr-ieee802-11/files/14021990/wifi_tx.zip)**

Running **wifi_beacon_tx.grc** is not giving any error, But still I'm not able to see the Beacons.
Im i missing anything here, please help.
![Screenshot from 2024-01-23 15-42-24](https://github.com/bastibl/gr-ieee802-11/assets/157352391/ea3a1b41-35e3-465e-a1a9-44655c597b6d)

**Beacon frame generation using scapy:**
![Screenshot from 2024-01-23 15-38-59](https://github.com/bastibl/gr-ieee802-11/assets/157352391/2faccb7f-2321-4128-8d31-af8c2b6caab0)
![Screenshot from 2024-01-23 15-39-11](https://github.com/bastibl/gr-ieee802-11/assets/157352391/0b20799d-eb3b-4e11-a775-b1fe6281ae0d)

**GNU radio .grc (please find the attached zip for .grc file)**
![Screenshot from 2024-01-23 15-41-30](https://github.com/bastibl/gr-ieee802-11/assets/157352391/7d937d73-f91c-4363-a693-286571d90734)

**Comment by ShivaAlethea** [comment]
@bastibl 
Also tried the first scenario, No errors now.
Need a info >> on **FFT** >> **Window** (formula something like>> tuple(1/52**0.1.....))
[wifi_tx_1.zip](https://github.com/bastibl/gr-ieee802-11/files/14035244/wifi_tx_1.zip)
![Screenshot from 2024-01-24 13-32-51](https://github.com/bastibl/gr-ieee802-11/assets/157352391/6f416453-7707-4685-b0a0-d2975c058aa1)
![Screenshot from 2024-01-24 13-32-34](https://github.com/bastibl/gr-ieee802-11/assets/157352391/f5454009-a125-427f-a92b-ea5c074659ad)

**Comment by ShivaAlethea** [comment]
Hi @bastibl,
Tried to follow https://github.com/bastibl/gr-ieee802-11/issues/236 and observed below.
- If i try to capture PCAPs directly from the **Socket PDU**, It is working fine and I'm able to see some **Beacons**.
- But the same is **not working** with **WiFi PHY Hier**,  No packets are captured.

PCAP With >> Socket PDU - **Working**
![Screenshot from 2024-01-25 13-21-58](https://github.com/bastibl/gr-ieee802-11/assets/157352391/2af9ce4b-7aa3-4bf0-a124-9070b50ba332)
![Screenshot from 2024-01-25 13-43-48](https://github.com/bastibl/gr-ieee802-11/assets/157352391/58a91551-7d94-41e8-b012-39f738ec3e67)

PCAP With >> WiFi PHY Hier - **Not working**
![Screenshot from 2024-01-25 13-21-27](https://github.com/bastibl/gr-ieee802-11/assets/157352391/a89b968c-dd12-4679-b7d6-af0926ee4850)
![Screenshot from 2024-01-25 13-45-31](https://github.com/bastibl/gr-ieee802-11/assets/157352391/27fd83e9-7942-4366-b2d6-2908edbb996c)

**Comment by bastibl** [comment]
I already replied to the last post in the other issue.

The frequency that you are using (5.89GHz is not a WiFi channel but for vehicular networking, i.e., a normal device will not search there). Please try changing to a 11g or 11a channel.

Not sure about your issue with the FFT window. You shouldn't have to change it, if you use the correct version of the module, i.e., make sure that you use the branch of this module that fits your GNU Radio version.

**Comment by ShivaAlethea** [comment]
@bastibl Thanks for the support. [It](https://private-user-images.githubusercontent.com/157352391/298897148-7d937d73-f91c-4363-a693-286571d90734.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NzkzNjQsIm5iZiI6MTcwNjc3OTA2NCwicGF0aCI6Ii8xNTczNTIzOTEvMjk4ODk3MTQ4LTdkOTM3ZDczLWY5MWMtNDM2My1hNjkzLTI4NjU3MWQ5MDczNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwMVQwOTE3NDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xM2U0ZWI4NzI0NDlkNzVjNGQ0OWVlOWIwNDRmYmI2YmFhYjk2NmQ1ODZjNGNjZmRiNDQ4Y2U3NDA2OGY2YmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.va3HMEA5GUoIBlYHcvHo7zF4FVPGhMRefRxuMhvHKxg) started working fine after HackRF Firmware update.
Now im able to see my SSID's in laptop.
![Screenshot from 2024-02-01 11-51-44](https://github.com/bastibl/gr-ieee802-11/assets/157352391/987d8bf9-6b76-4921-8233-99696b57f73c)

**Comment by ShivaAlethea** [comment]
@bastibl 
Need one more clarification,
Is it possible to send multiple beacons from different ports and frequencies ?
Something Like:
![Screenshot from 2024-02-07 12-31-58](https://github.com/bastibl/gr-ieee802-11/assets/157352391/6172c37d-e06f-45fa-846e-53539006f96e)

**Trying to run this test is giving :** 
RuntimeError: resolve_port: hierarchical block 'sink_impl': input 1 is not connected internally

```
File "/home/alethea/shiva/HackRF/gr-ieee802-11/examples/playback_test.py", line 200, in <module>
    main()
  File "/home/alethea/shiva/HackRF/gr-ieee802-11/examples/playback_test.py", line 180, in main
    tb.start()
  File "/usr/lib/python3/dist-packages/gnuradio/gr/top_block.py", line 116, in start
    top_block_start_unlocked(self._impl, max_noutput_items)
RuntimeError: resolve_port: hierarchical block 'sink_impl': input 1 is not connected internally

```
Anything else needs to be taken care here?

**Comment by bastibl** [comment]
This not possible with the HackRF.

**Comment by ShivaAlethea** [comment]
@bastibl Thank you very much for your support.
Closing this issue as it started working for me after firmware update.
