### ISSUE TITLE
Filtering IQ samples using MAC address

### ISSUE THREAD

**Issue by smazokha** [bastibl/gr-ieee802-11#401]
Dear @bastibl,

First of all, thank you for taking the time to maintain this project, and review my question!

I'm trying to filter out IQ samples (captured on 2.4 GHz 7th channel) from my transmitter using its MAC address. I confirmed that the samples I captured contain frames from my transmitter. But they also hold traffic from the access point with which I'm communicating with (sending ping requests to it).

My end goal is to use filtered samples to estimate transmitter's DoA (samples are captured across 4 antennas, using X310 USRPs, synchronized via octoclock and phase-calibrated).

Given the above, I have the following questions:

1. Is there a way to filter IQ frames from the transmitter via its MAC address? (perhaps, there's a way to identify index at which a frame with a given MAC address begins?)

2. If (1) is not feasible, would it be possible to leverage CSI to estimate DoA? I found a [similar thread](https://github.com/bastibl/gr-ieee802-11/issues/263), but it doesn't seem like there's a clear answer to whether estimating DoA using CSI is possible, if the signal is octoclock-synchronized and phase-calibrated.

Thank you in advance for your help!

Sincerely,
Stephan

**Comment by bastibl** [comment]
Hi Stephan,

Regarding 1.: When you save IQ frames, you can store at which sample it started (`nitems_read`). You can also annotated this information as metadata (in form of an item tag). The SyncShort block already does this to propagate the frequency offset, for example. https://github.com/bastibl/gr-ieee802-11/blob/maint-3.10/lib/sync_short.cc#L139-L147

It requires adapting the downstream blocks to forward this information accordingly. But then you also have it available at the decoder. You can connect a `MessageDebug` block the `mac_out` port of  the PHY and will see that the decoded packet still has this metadata attached. 

Then it depends on you, if you create a new GNU Radio block that correlate this two streams, or if you log it and do post-processing.

Regarding 2.: I'm not so deep into DSP. I know Martin Braun did a PhD about OFDM radar. But in general, the people in GNU Radio Matrix chat and the mailing list will be able to help you much better than me. My guess would be, differentiating senders is easy, estimating the DoA of a particular sender is hard :-)

Best,
Bastian

**Comment by smazokha** [comment]
Hi Bastian,

Thank you so much for your reply! This is very helpful. I will close the issue for now and report back once I have some results. 

Sincerely,
Stephan
