### ISSUE TITLE
gr-ieee802-11for bladerf?

### ISSUE THREAD

**Issue by liiso7** [bastibl/gr-ieee802-11#403]
Does this work for bladerf2.0? Why did I run wifi_tx.grc and wifi_rx.grc without producing any results（Replaced the USRP source/sink modules with osmocom source and sinks
respectively.）

**Comment by bastibl** [comment]
I don't see a reason why it shouldn't work. If you need help setting it up, you have provide more information about your setup and what you are doing.

**Comment by liiso7** [comment]
1.wifi_loopback.grc works, and here's what I got:
![wifi_loopback grc](https://github.com/bastibl/gr-ieee802-11/assets/110809805/5810b79b-f44e-40ed-87bf-3fe89c655a62)
2.. I use wifi_tx.grc to send data packets, and use monitor mode wireless network card to receive data at the same frequency. The receiver wireshark did not see any data packets sent by wifi_tx.grc, and wifi_tx.grc generated file wifi.bin without any content. Here is my wifi_tx.grc flowchart:
![wifi_tx](https://github.com/bastibl/gr-ieee802-11/assets/110809805/a777d9d3-8000-48e6-ae02-b432082e45f5)
3. I use wifi_tx.grc to send packets and wifi_rx.grc to receive packets at same frequency, but it does not produce any results, here is my wifi_rx.grc flow diagram:
![wifi_rx](https://github.com/bastibl/gr-ieee802-11/assets/110809805/0de5b4bd-ec7b-4de8-ae9a-5f80e43b645d)

**Comment by bastibl** [comment]
That `wifi.bin` is empty is as expected. At this output received frames would show up, but this is a TX flowgraph. The rest looks fine. I'd suggest to test different parameters (esp. gain), check all parameters again, and maybe add more padding in the PacketPad 2 block at the transmitter.

**Comment by liiso7** [comment]
Now I can receive a small number of data frames sent by wifi_tx.grc through the wireless network card, but the sequence number of data frames is not consecutive, that is to say, packet loss occurred in the transmission process, may I ask what causes this? What is the data transmission packet loss rate for this project?

**Comment by bastibl** [comment]
Hard to tell. This can have many causes. Interference, gain too high, gain too low, wrong antenna, antenna at wrong port, pc too slow, SDR has an uncompensated DC offset, ... any many more. I've seen all of this in the past.
