### ISSUE TITLE
Estimating Angle of arrival and distance from CSI values in Frame Equalizer

### ISSUE THREAD

**Issue by Sourya17** [bastibl/gr-ieee802-11#404]
Hi!
I am quite new to GNU Radio as well as this 802.11 module. I was able to print the CSI values from the Frame Equalizer method in your repo. But I want to know wether your project allows to calculate the Angle of Arrival and distance of the wave impinging on any of the Rx antennas? If not, could the CSI values being printed from the frame equalizer method after get_csi( ) be utilized to find the AoA and distance? Help will really be appreciated.

**Comment by bastibl** [comment]
Estimating the AoA is not supported by this module. It only gives you CSI. What you do with these values is up to you.

The CSI can be visualized/processed as shown in the loopback flowgraph.
