### ISSUE TITLE
How to use this repo to view WiFi Halow (802.11ah)?

### ISSUE THREAD

**Issue by Jake-Howell** [bastibl/gr-ieee802-11#405]
Hi, i'm really happy to come across this repo so thanks for making it!

I have followed your instalation guide and it all looks like it's running well with the supported WiFi bands, however i'd like to use this to view WiFi Halow (sub GHz WiFi) and would like to know if it's possible to change a few parameters in the WiFi_rx flow graph to do this.
So far, i've changed the BW to 1 MHz and the frequency to 863.5MHz, but I can imagine that it's not as simple as that as I don't get a usable output.

If you could let me know your thoughts id really appreciate it. 
Thanks :)

**Comment by bastibl** [comment]
Some 11ah configs are close to this but this will not work out of the box. 11ah supports much more frame configurations and also uses different subcarrier configurations (52 vs 48 data subcarriers). So even the modes that are very similar to 11a will need some adaption. See: https://en.wikipedia.org/wiki/IEEE_802.11ah
