### ISSUE TITLE
[Feature request] Support others SDR hardware devices

### ISSUE THREAD

**Issue by ohault** [bastibl/gr-ieee802-11#409]
Currently, gr-ieee802-11 would only support a very short list of SDR hardware.

The use of [SoapySDR API](https://github.com/pothosware/SoapySDR/wiki) as a neutral and platform independent SDR support library could perhaps provide a way for gr-ieee802-11p to support others SDR hardware devices.

**Comment by bastibl** [comment]
The module can be used with Soapy by replacing the source/sink blocks of the flowgraphs. This has been done already without any problems that I am aware of. Did you experience any issues?
