### ISSUE TITLE
updation needed for IEEE 802.11n packet capturing

### ISSUE THREAD

**Issue by Bala26TN** [bastibl/gr-ieee802-11#411]
Greatings,
this project has helped me a lot, i would like to know how can this be updated for capturing all modes of WIFI that include IEEE 802.11(n/ac/ax) also, can u help me with the updated and extra blockes to be added for doing the same.
thanks in advance.

**Comment by bastibl** [comment]
Very happy that the project helped you. Extending it for other standards would be a major effort, as they differ in bandwidth, preamble, codes (e.g., LDPC vs convolutional codes), MIMO, etc. etc. Also doing >=80MHz and higher MIMO orders on the CPU, might be hard. If you want to give it a try, I'd generate a reference frame (for example with the MATLAB WiFi Toolbox) and use the standard to come up with code to decode the reference frame.

**Comment by Bala26TN** [comment]
thank you for the response
where can i get the code where u have generated the reference frame and decoded it.
basically i have to capture all WIFI packets that are present in the surrounding. but i am missing those devices having WIFI IEEE802.11n that why i have posted the query.

**Comment by bastibl** [comment]
I didn't use a reference frame, but I should have. You can just look for example for the MATLAB toolbox. https://de.mathworks.com/products/wlan.html
But, again, this will be a major effort. I'd assume 6 to 12 months.

**Comment by Cobi-Coder** [comment]
@Bala26TN Have you completed the 802.11n project with SDR?
