### ISSUE TITLE
An error in block <chunks_to_symbols> 

### ISSUE THREAD

**Issue by Ullr1** [bastibl/gr-ieee802-11#413]
Hi,
I am using the block <chunks_to_symbols> and there is something that confused me. 
First, a error occurred as "no encoding in input stream". Then I located on  `    if (tags.size() != 1) {
        throw std::runtime_error("no encoding in input stream");
    }` at line 59 in chunks_to_symbols_impl.cc. I have printed the variable tags.size() and it equals to 0, so that seems to be where the error came from. But here's what I don't understand `    : tagged_stream_block("chunks_to_symbols",
                          io_signature::make(1, 1, sizeof(char)),
                          io_signature::make(1, 1, sizeof(gr_complex)),
                          "packet_len")`  at line 30 in chunks_to_symbols_impl.cc , it means that this only accepts tagged streams whose tagged key is "packet_len". And `    get_tags_in_range(
        tags, 0, nitems_read(0), nitems_read(0) + ninput_items[0], pmt::mp("encoding"));`at line 57, it means that this only return tags whose key is "encoding". So aren't these two places in conflict. Then it was inevitable that tags.size() equals to 0. 
Is there any problem with my understanding? Look forward to your reply.

Best wishes.

**Comment by bastibl** [comment]
I'm not sure what you are trying to do. You can add a Tag Debug block to the upstream block in the original flowgraph to understand what tags it requires.
