### ISSUE TITLE
Problem compiling

### ISSUE THREAD

**Issue by rwnobrega** [bastibl/gr-ieee802-11#48]
Hi! I get the following error while compiling

```
/home/rwnobrega/Projects/gr-ieee802-11/lib/utils.h:32:64: error: expected ‘;’ before ‘}’ token
 #define mylog(msg) do { if(d_log) { GR_LOG_INFO(d_logger, msg) }} while(0);
```

Putting the ‘;’ before ‘}’ apparently fixes the problem.

**Comment by bastibl** [comment]
Looks like some compilers are stricter than others. Thanks for bringing this up, I just pushed a commit with the suggested fix. Let me know if you still have problems.

**Comment by rwnobrega** [comment]
Problem solved. Thank you so much!
