### ISSUE TITLE
foo_swig.py

### ISSUE THREAD

**Issue by ddqq289738312** [bastibl/gr-ieee802-11#52]
Hi,

I followed the instructions and successfully installed gr-ieee802-11. But when I run wifi_loopback.grc, I got the following error:
File "/usr/local/lib/python2.7/dist-packages/foo/__init__.py", line 45, in <module>
    from foo_swig import *
ImportError: No module named foo_swig

I think there should have a "foo_swig.py" file in "/usr/local/lib/python2.7/dist-packages/foo/", but there isn't in my system. I also checked swig version by "swig -version", it shows:
SWIG Version 3.0.8

Compiled with g++ [x86_64-pc-linux-gnu]

Configured options: +pcre

what did I do wrong?

Thanks

**Comment by bastibl** [comment]
This is a gr-foo issue.
Yes, there should be a foo_swig.py file, so somethings went wrong during its installation. Please rebuild gr-foo and check for warnings or errors during the process.
