### ISSUE TITLE
installation issue on hackrf with ubuntu

### ISSUE THREAD

**Issue by chakpongchung** [bastibl/gr-ieee802-11#54]
cpchung:build$ cmake ..
-- Build type not specified: defaulting to release.
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   filesystem
--   system
--   thread
--   chrono
--   date_time
--   atomic
Checking for GNU Radio Module: RUNTIME
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.9
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
-- Found GNURADIO_RUNTIME: /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so  
GNURADIO_RUNTIME_FOUND = TRUE
Checking for GNU Radio Module: PMT
-- Checking for module 'gnuradio-runtime'
--   Found gnuradio-runtime, version 3.7.9
 * INCLUDES=/usr/include
 * LIBS=/usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so
-- Found GNURADIO_PMT: /usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so;/usr/lib/x86_64-linux-gnu/libgnuradio-pmt.so  
GNURADIO_PMT_FOUND = TRUE
-- Checking for module 'cppunit'
--   Found cppunit, version 1.13.2
-- Found CPPUNIT: /usr/lib/x86_64-linux-gnu/libcppunit.so;dl  
-- 
-- Checking for module SWIG
-- Found SWIG version 2.0.12.
-- Found SWIG: /usr/bin/swig2.0  
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found suitable version "2.7.12", minimum required is "2") 
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.12", minimum required is "2") 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of unsigned int
-- Check size of unsigned int - done
-- Check size of unsigned long
-- Check size of unsigned long - done
-- Check size of unsigned long long
-- Check size of unsigned long long - done
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE
-- Performing Test HAVE_WNO_UNUSED_BUT_SET_VARIABLE - Success
-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
UHD_INCLUDE_DIRS (ADVANCED)
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
   used as include directory in directory /home/cpchung/sdr/gr-foo/lib
UHD_LIBRARIES (ADVANCED)
    linked by target "gnuradio-foo" in directory /home/cpchung/sdr/gr-foo/lib

-- Configuring incomplete, errors occurred!
See also "/home/cpchung/sdr/gr-foo/build/CMakeFiles/CMakeOutput.log".
See also "/home/cpchung/sdr/gr-foo/build/CMakeFiles/CMakeError.log".

**Comment by bastibl** [comment]
one of the blocks uses UHD specific features, which makes UHD a dependency.
Ideally that would be detected by cmake (if you know some cmake -- patches are very welcome), but for now, you will have to install UHD.
