### ISSUE TITLE
thread[thread-per-block[18]: <block mac (26)>]: Frame too large (> 1500)

### ISSUE THREAD

**Issue by chakpongchung** [bastibl/gr-ieee802-11#55]
when I try to use the wifi_tx.grc to transmit a message, it says the above error.

what is that?

thread[thread-per-block[18]: <block mac (26)>]: Frame too large (> 1500)
![2](https://cloud.githubusercontent.com/assets/8110904/20770198/e0a892b4-b712-11e6-82ae-4d7b70dea3a8.png)

**Comment by bastibl** [comment]
It means the frame is too large (seemingly larger then 1500 byte).
I just tried and the error doesn't occur here. Maybe you want to reset the flow graph to the original version.
If this is the exact configuration that you tried, then it looks like you would receive very large frames over the UDP Server.

**Comment by chakpongchung** [comment]
Thanks!

Looks like I need to fine tune the size of the message. I was using

pmt.intern("".join("hello!" for i in range(pdu_length)))

Now I changed to 

pmt.intern("hello!")


Problem resolved.
