### ISSUE TITLE
Regarding CSMA/CA Mechanism 

### ISSUE THREAD

**Issue by raghu25** [bastibl/gr-ieee802-11#57]
Is the a CSMA/CA mechanism in your gr-ieee802.11 code which can be implemented on USRP and general purpose PC

**Comment by bastibl** [comment]
It's in the 'csma_and_agc' branches of my repos. Note, you will also have to adapt GNU Radio and UHD.

**Comment by Zhijing1128** [comment]
Hi @bastibl 

I tried the non-CSMA/CA version, I got ~15% packet loss rate (received by WiFi card, SNR ~30dB). Is the high packet loss due to the absence of CSMA/CA?

**Comment by bastibl** [comment]
Depends on your setup. Also without CSMA you can easily receive all frames. But maybe not on the 2.4GHz band with hundreds of devices in the same interference domain.
