### ISSUE TITLE
ubuntu 16.04LTS, cannot find some of the blocks after installation

### ISSUE THREAD

**Issue by chakpongchung** [bastibl/gr-ieee802-11#60]
![image](https://cloud.githubusercontent.com/assets/8110904/21621427/ec98ef50-d1c6-11e6-84f3-dba4ad556a3a.png)

**Comment by bastibl** [comment]
That's not related to blocks, but probably because of a wrong python path. See the console output for information.
Also try to import ieee80211 in python directly (in an interactive session).

See here, for more detailed instructions:
https://www.wime-project.net/installation/

**Comment by chakpongchung** [comment]
Thank you for the pointer!

Adding this line to ~/.bashrc solved my problem:

export PYTHONPATH=/usr/local/lib/python2.7/site-packages:${PYTHONPATH}
