### ISSUE TITLE
About MAC parse

### ISSUE THREAD

**Issue by LilyZL** [bastibl/gr-ieee802-11#63]
Hi,

I'm confused about one thing when I running the code. I found that there are lots of frames re too short to be parsed. And all of them are:

frame too short to parse (<20)
WIRESHARK: received new message
message length 10
WIRESHARK: d_msg_offset: 0   to_copy: 43   d_msg_len 43
WIRESHARK: output size: 32768   produced items: 43

Why the length of these frames is 10?

**Comment by bastibl** [comment]
...because whatever was decoded had a payload length of 10 byte.
Such questions can easily be answered by having a quick look at the code
https://github.com/bastibl/gr-foo/blob/next/lib/wireshark_connector_impl.cc#L194
