### ISSUE TITLE
gr-ieee80211 and the bladeRF

### ISSUE THREAD

**Issue by bnt2025** [bastibl/gr-ieee802-11#64]
Hello,

I have modified the wifi_rx example to use the osmocom source instead of the uhd source. The application runs but I receive very little Wi-Fi data in wireshark.  The only packets I actually can decode are RTS and CTS with the occasional Ack. 

I never receive any Beacons or other packets. What would cause this to happen?

Thank in advance

**Comment by bastibl** [comment]
See here for ideas:
https://www.wime-project.net/installation/

If you still have problems, could you please provide a more verbose description including of what doesn't work. (like overruns, underruns, gain, frame detection is triggered all the time, frame detection is never triggered, etc. etc.)
