### ISSUE TITLE
Packet-level TX power change

### ISSUE THREAD

**Issue by Zhijing1128** [bastibl/gr-ieee802-11#70]
Hi,

how can I randomly change the TX power for every packet?

Thanks.

**Comment by bastibl** [comment]
The question doesn't have much to do with the WiFi transceiver. In the end you will have to attach a tag to the start of the frame. Then, the tag has to be interpreted by the SDR sink. If you use an SDR from Ettus, this page might be relevant
http://gnuradio.org/doc/doxygen/page_uhd.html

**Comment by Zhijing1128** [comment]
Thanks for the reply.

I'm thinking of changing the gain along w/ the time since we send packets as time changes. It's easier. But I'm not sure whether there will be some issues in this approach. 

Thanks in advance!

**Comment by bastibl** [comment]
Sorry, but I have no idea what you are asking for. But since it's not specific to WiFi (but to GNU Radio and your SDR) and since it's not an issue (but a general question), you should post this question to the GNU Radio mailing list. Also consider describing you question in more than one sentence.
