### ISSUE TITLE
How to disable RTS/CTS mechanism

### ISSUE THREAD

**Issue by 2016JTM2091** [bastibl/gr-ieee802-11#73]
Hi,
As you have mentioned because of the latency issue we have to set the number of ACK retries to zero and also disable the RTS/CTS mechanism.
Please tell me how to do this from flow graph.
Thank you.

**Comment by bastibl** [comment]
Hi, there seems to be a misunderstanding. ACK and RTS/CTS is not part of this module. On Linux there is the `iw` tool to configure WiFi cards. If you have problems with this tool (in combination with a particular WiFi card), you can find help on the linux-wireless mailing list.
