### ISSUE TITLE
gr-foo :Installation error

### ISSUE THREAD

**Issue by wshe1** [bastibl/gr-ieee802-11#85]
Dear  Bastian Bloessl 
         I have the honor to see the paper named "Performance Assessment of IEEE 802.11p with an Open Source SDR-based Prototype" in the TMC.  I want to use your software. But there was an error during the installation of the software gr-foo, as follows: fatal error:gnuradio/filter/mmse_resampler_cc.h:No such file or directory.
     Experimental environment:  Ubuntu 16.04, gnuradio 3.7.11.  I did not find the wrong reason, hope you can give me an answer.
![tim 20171025184836](https://user-images.githubusercontent.com/33091503/31998195-7bbcca8e-b9c1-11e7-9242-f6889b970d68.png)

**Comment by bastibl** [comment]
Hi, the problem with gr-foo was already reported in the gr-foo repo
https://github.com/bastibl/gr-foo/issues/6

In short, you have to use the next branch of gr-foo with the next branch of GNU Radio and the master branch of gr-foo with the master branch of GNU Radio.
