### ISSUE TITLE
wifi_loopback.grc's issue

### ISSUE THREAD

**Issue by wshe1** [bastibl/gr-ieee802-11#86]
Dear Bastian Bloessl
   I have encountered a problem in testing wifi_loopback.grc，as follows：

Loading: "/home/wshe/gr-ieee802-11-master/examples/wifi_phy_hier.grc"
>>> Done

Generating: '/root/.grc_gnuradio/wifi_phy_hier.py'

Loading: "/home/wshe/gr-ieee802-11-master/examples/wifi_loopback.grc"
linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

>>> Done
/usr/local/lib/python2.7/dist-packages/gnuradio/grc/main.py:54: GtkWarning: Attempting to store changes into `/root/.local/share/recently-used.xbel', but failed: Failed to create file '/root/.local/share/recently-used.xbel.MWIU8Y': No such file or directory
  gtk.main()
/usr/local/lib/python2.7/dist-packages/gnuradio/grc/main.py:54: GtkWarning: Attempting to set the permissions of `/root/.local/share/recently-used.xbel', but failed: No such file or directory
  gtk.main()

Generating: '/home/wshe/gr-ieee802-11-master/examples/wifi_loopback.py'
>>> Warning: This flow graph may not have flow control: no audio or RF hardware blocks found. Add a Misc->Throttle block to your flow graph to avoid CPU congestion.

Executing: /usr/bin/python2 -u /home/wshe/gr-ieee802-11-master/examples/wifi_loopback.py

linux; GNU C++ version 5.3.1 20151219; Boost_105800; UHD_003.009.002-0-unknown

MAPPER: encoding: 0
set_min_output_buffer on block 9 to 397056
set_min_output_buffer on block 11 to 397056
set_min_output_buffer on block 13 to 397056
set_min_output_buffer on block 14 to 397056
set_min_output_buffer on block 16 to 397056
set_min_output_buffer on block 31 to 96000

>>> Done
 

    I can not see some decoded 'Hello World' packets in the console. I did not find the wrong reason, hope you can give me an answer.

**Comment by bastibl** [comment]
Looks OK. The current version doesn't send "hello world", but a string of 'x's of variable length.

https://github.com/bastibl/gr-ieee802-11/issues/82
