### ISSUE TITLE
Issue  installing the gr-foo 

### ISSUE THREAD

**Issue by yxs33** [bastibl/gr-ieee802-11#89]
![default](https://user-images.githubusercontent.com/27758520/33930381-aa44960c-e027-11e7-8cc6-6fa2268bc9ab.png)
I don't know why gnuradio don't have the mmse_resampler_cc.h file,please help me

**Comment by yxs33** [comment]
here are the version
![default](https://user-images.githubusercontent.com/27758520/33931606-7141fa62-e02b-11e7-9197-f8ac0dc3f20f.png)

**Comment by bastibl** [comment]
This was addressed several times on the mailing list and in various issues. In short: you have to read the readme until the second sentence.
