### ISSUE TITLE
Error: Block key "wifi_phy_hier" not found

### ISSUE THREAD

**Issue by Avishek888** [bastibl/gr-ieee802-11#91]
I was using the wifi_transceiver.grc and getting the following error.
>>> Error: Block key "wifi_phy_hier" not found
>>> Error: Block key "wifi_phy_hier" not found
![wifi_transceiver](https://user-images.githubusercontent.com/32855419/34129586-a53548e8-e412-11e7-87a9-cf1f8dea9d00.png)

**Comment by bastibl** [comment]
Citing from the readme:

OFDM PHY
The physical layer is encapsulated in a hierarchical block to allow for a clearer transceiver structure in GNU Radio Companion. This hierarchical block is not included in the installation process. You have to open /examples/wifi_phy_hier.grc with GNU Radio Companion and build it. This will install the block in ~/.grc_gnuradio/.
