### ISSUE TITLE
Issue with branch agc_and_csma

### ISSUE THREAD

**Issue by Mayupeng1** [bastibl/gr-ieee802-11#94]
when I open the example I find there had a 'Missing block',what should  I do?
![qq 20180124112937](https://user-images.githubusercontent.com/35753503/35317291-08948cee-0111-11e8-9312-5aba77ed8d01.png)

**Comment by bastibl** [comment]
Using CSMA is quite complicated since you have to also modify GNU Radio and UHD. See the corresponding branches of my forks of these repositories.

**Comment by Mayupeng1** [comment]
Thank you very much for your prompt reply！ I'll try to solve the problem.
