### ISSUE TITLE
Issue with receiving  wifi signal

### ISSUE THREAD

**Issue by ynyn11121** [bastibl/gr-ieee802-11#98]
Hello Bastian, i'm using your tool with a usrp b210, a wifi card, a laptop and a desktop
I connect wifi card with my laptop, connect usrp b210 with my desktop, by using wifi_rx.grc ,I cannot receive wifi signals, I don not know how to configure my wifi card .

I use a router to set my wifi signal is  802.11g  11 channel, then use my wifi card to surf the internet ,but my usrp still cannot catch good wifi signals.

**Comment by ynyn11121** [comment]
These pictures can help tell what I want ro say,
![0bf1b78b2c3d45f308eb3753a78f9ca5](https://user-images.githubusercontent.com/35592401/35793619-56e0c608-0a8d-11e8-93e9-1824e42437e4.jpg)
![Uploading 9A413B2B05AA421429B5358446B008C7.jpg…]()
![Uploading E1D40589F2FFB747FEADEFF3AF484F7C.jpg…]()

**Comment by bastibl** [comment]
I'm sorry but these pictures are not too helpful. I'm not sure what you are trying to communicate with them. What you are saying is "I tried; it didn't work". It would be helpful if you could be a bit more specific.

**Comment by ynyn11121** [comment]
Sorry，my English is not good，so i just want to express  by picture.
What I want  to say is : 
I use a router to set my wifi signal is 802.11g and 11 channel 2.462Ghz, but my usrp still cannot catch good wifi signals by using wifi_rx.grc.

**Comment by ynyn11121** [comment]
Thank you so much, I  just study about SDR  for 3days, so  many technical details are not very clear for me.

**Comment by ynyn11121** [comment]
My experiment result is ,I do not know what my problem is.
![9a413b2b05aa421429b5358446b008c7](https://user-images.githubusercontent.com/35592401/35794670-96a43fa0-0a91-11e8-9276-6503228d63f6.jpg)

**Comment by bastibl** [comment]
Looks like you modified the flow graph, so it's hard to tell what's going wrong. I'd recommend you use the unmodified flow graph from the repository (you changed the sample rate. Unfortunately, the receiver does not support 40MHz/11n. It's more then just setting the sample rate to 40Mhz....).
To avoid potential problems, I'd recommend you open the AP in the 5GHz band. On 2.4GHz, the card might operate in a backward compatible mode that is not supported by the module.
