### ISSUE TITLE
wifi_loopback.py is not going through ieee802_11_decode_mac (171/177 symbols)

### ISSUE THREAD

**Issue by lo-bert** [bastibl/gr-ieee802-11#99]
Hi Bastian, thanks for your effort in reading this Issue. 
After the preliminary steps, building **_wifi_phy_hier.grc_** with some debug options active, and running **_wifi_loopback.grc_**, I notice that no messages reach the **ieee802_11_parse_mac** block. 
This because the receiver block **ieee802_11_decode_mac** can't decode any MAC layer packet. It always receives only 171 symbols over 177 (for PDU = 500 / 528 with frame, at the sender). This repeats over and over again.

additional **ieee802_11_decode_mac** debug output is the line (at each new packet beginning parsed): 
`Decode MAC: frame start -- len 528  symbols 177  encoding 0`

May you help me in fixing the issue? Thanks,
Lorenzo

![screenshot from 2018-02-06 16-55-35](https://user-images.githubusercontent.com/36210107/35886636-ba5ab8e2-0b5f-11e8-8ae0-ac7e365d7478.png)

**Comment by lo-bert** [comment]
Additional Info:

 

- I can correctly receive 802.11 MAC packets over the Radio interface with **_wifi_rx.grc_**

- radio-config-info--version
3.7.9

**Comment by bastibl** [comment]
Maybe you modified the flow graph? It's not in the picture, but since you don't have Wireshark block installed, I assume that you also deleted the Packet Pad block. Please make sure the unmodified flow graph works.

**Comment by lo-bert** [comment]
Hi Bastian, thanks for your response.
A clean Installation of the master branches fixed it. Sorry for the useless thread. 
I'll close it.
